INSERT INTO Spell
(Spell_ID, Book_ID, Spell_Name, Spell_School, Spell_Subschool,
Spell_Descriptor, Spell_Components, Spell_Casting_Time, Spell_Range,
Spell_Effect, Spell_Target, Spell_Duration, Spell_Saving_Throw,
Spell_Resistance, Spell_Short_Description, Spell_Description,
Spell_Material_Component, Spell_Focus, Spell_XP_Cost)
VALUES
    (720,5,"Algid Enhancement","Transmutation",null,"Cold","V, S, Coldfire",
    "1 round","Close",null,"One cold creature/level","24 hours",
    "None","No",
    "Grant bonuses to creatures of the cold subtype.",
    "<p>You energize cold creatures with a surge of coldfire. Creatures with the cold subtype affected by this spell gain a +1 deflection bonus to AC, +1d8 temporary hit points, a +1 enhancement bonus on attack rolls, and a +2 bonus on saving throws against fire effects. Each of these enhancements increases by +1 for every three caster levels. So a 12th-level caster grants a +5 deflection bonus to AC, an extra 1d8+4 temporary hit points, a +5 enhancement bonus on attack rolls, and a +6 resistance bonus on saving throws against fire effects.</p><p>This spell has no effect on creatures not of the cold subtype.</p>",
    "Coldfire component: One ounce of coldfire.",
    null,null),
        
    (721,5,"Animate Snow","Transmutation",null,"Cold","V, S, M",
    "1 standard action","Medium","Up to a 20-ft. cube of snow",null,"1 round/level",
    "None","No",
    "Turns snow into creatures to fight for you.",
    "<p>You imbue a mass of fallen snow with mobility and a semblance of life. The snow to be animated may be natural or magically created. Snow animated by this spell is treated as an animated object. You can animate four Large animated objects, two Huge animated objects, or one Gargantuan animated object. For details, see the Animated Object entry, page 13 of the <em>Monster Manual</em>. The animated snow can assume any basic shape you wish, and it attacks as directed by your vocal commands. Animated snow objects possess the Blind and Trample special attacks as detailed in the <em>Monster Manual</em> entry for animated objects. In addition, they have the cold subtype, and do an additional 1d6 points of cold damage on a successful hit.</p><p>Animated snow objects take 1d6 points of damage each round if they exist in a place with temperatures above freezing.</p>",
    "Material Component: Meltwater from a glacier.",
    null,null),

    (722,5,"Anticold Sphere","Abjuration",null,null,"V, S",
    "1 standard action","10 ft.","10-ft.-radius emanation, centered on you",null,"10 min./level (D)",
    "None","Yes",
    "Mobile energy field provides immunity to cold.",
    "<p>You bring into being a mobile, spherical energy field that protects against cold. All creatures within the area of the spell are granted immunity to cold. In addition, the sphere prevents the entrance of any creature with the cold subtype. The effect hedges out such creatures in the area when the spell is cast.</p><p>This spell may be used only defensively, not aggressively. Forcing an abjuration barrier against creatures that the spell keeps at bay collapses the barrier (see Abjuration, page 172 of the <em>Player's Handbook</em>).</p>",
    null,null,null),
    
    (723,5,"Arctic Haze","Conjuration","Creation","Cold","V, S",
    "1 standard action","Medium","Fog spreads in a 30-ft. radius, 20 ft. high",null,"10 min./level",
    "Fortitude half","No",
    "Fog obscures vision and deals 4 cold damage per round.",
    "<p>A bank of fog composed entirely of razor-sharp ice shards billows out from the targeted point. The fog obscures all sight, including darkvision, beyond 5 feet. A creature 5 feet away has concealment (20% miss chance). Creatures farther away have total concealment (50% miss chance, and the attacker can't use sight to locate the target).</p><p>In addition, the sharp ice particles tear the skin of those moving through the area, causing 4 points of damage per round, half of which is cold damage.</p><p>A strong wind (21+ mph) diserses the fog in 4 rounds; a severe wind (31+ mph) disperses the fog in 1 round. Dispersing the fog in this manner, however, causes damage to those within the area as the icy shards whip past. A strong wind causes 4 points of damage per round (half cold); a severe wind causes 8 points of damage (half cold).</p>",
    null,null,null),
    
    (724,5,"Aura of Cold, Greater","Transmutation",null,"Cold","V, S, DF",
    "1 standard action","10 ft.","10-ft.-radius spherical emanation, cenetered on you",null,"1 round/level (D)",
    "None","Yes",
    "Intense cold deals 2d6 damage to creatures within 10 ft.",
    "<p>This spell functions exactly like <em>lesser aura of cold</em>, except it deals 2d6 points of cold damage to all creatures within 10 feet.</p><p>Lesser aura of cold's description is added below, for convenience:</p><p>You are covered in a thin layer of white frost and frigid cold emanates from your body, dealing 1d6 points of cold damage at the start of your round to each creature within 5 feet.</p>",
    null,null,null),

    (725,5,"Aura of Cold, Lesser","Transmutation",null,"Cold","V, S, DF",
    "1 standard action","5 ft.","5-ft.-radius spherical emanation, centered on you",null,"1 round/level (D)",
    "None","Yes",
    "Intense cold deals 1d6 damage to creatures within 5 ft.",
    "<p>You are covered in a thin layer of white frost and frigid cold emanates from your body, dealing 1d6 points of cold damage at the start of your round to each creature within 5 feet.</p>",
    null,null,null),

    (726,5,"Binding Snow","Transmutation",null,"Cold","V, S, DF, Frostfell",
    "1 standard action","Medium","One 10-ft. square/level",null,"1 hour/level (D)",
    "Reflex negates","Yes",
    "Snow freezes, impeding movement",
    "<p>This spell must be cast on a snow field. That snow field instantly freezes, impeding movement through the area. A creature caught within the area can move only at half its normal speed. By making a DC 20 Strength check or a DC 25 Escape Artist check, the creature can move at its normal speed for that round. A creature that succeeds on a Reflex save is not impeded.</p>",
    null,null,null),

    (727,5,"Blizzard","Transmutation",null,"Cold","V, S",
    "1 round","Long","100 ft.-radius/level spread",null,"1 round/level",
    "Fortitude partial","No",
    "Temperature drops and powerful blizzard reduces visibility to zero.",
    "<p>Immediately upon completion of this spell, the temperature drops to below freezing and a powerful blizzard erupts in the area. Visibility is reduced to zero, making Spot, Search, and Listen checks and all ranged attacks impossible. Unprotected flames are automatically extinguished and protected flames have a 75% chance of being doused. Creatures unprotected from the cold must make a Fortitude save or take 1d6 points of nonlethal cold damage.</p><p>One foot of new snow falls each round. Movement within the area is impeded, depending on the creature's size and depth of snow (for movement in a snow field, see page 12 of <em>Frostburn</em>).</p>",
    null,null,null),
    
    (728,5,"Blood Snow","Necromancy",null,"Cold","V, S",
    "1 standard action","Medium","20-ft. square of snow/level",null,"1 round/level",
    "Fortitude negates","Yes",
    "Area of fallen snow drains 1d2 points of Con/round and causes nausea.",
    "<p>You must cast this spell on a snow field. You corrupt an area of fallen snow, imbuing it with negative energy. Each round, a creature in contact with blood snow must succeed on a Fortitude save or take 1d2 points of Constitution drain. In addition, anyone failing a saving throw is nauseated for the duration of the spell.</p>",
    null,null,null),

    (729,5,"Bone Chill","Necromancy",null,null,"V, S, M",
    "1 standard action","Close","Ray",null,"1 round/level",
    "Fortitude negates","No",
    "Corporeal undead are held by a thick layer of frost.",
    "<p>A ray of burning cold erupts from your fingertips. Corporeal undead struck by the ray are covered in a layer of ice, rendering the subject immobile as if <em>held</em>. Each round on its turn, the subject may attempt a new saving throw to break free of the ice. (This is a full-round action that does not provoke attacks of opportunity.)</p>",
    "Material Component: A small piece of bone and a 1-inch cube of ice.",
    null,null),
    
    (730,5,"Boreal Wind","Evocation",null,"Cold","V, S, DF",
    "1 standard action","Long","Gust of wind (20 ft. wide, 20 ft. high) emanating out from you to the extreme of the range",null,"1 round + 1 round/2 levels",
    "Fortitude negates","Yes",
    "Gust of cold wind deals 1d4 cold damage/level and knocks creatures back.",
    "<p>You create a strong blast of arctic air that originates from your fingertips and moves in the direction you are facing. As a stronger form of <em>gust of wind</em>, this boreal wind automatically extinguishes candles, torches, and similar protected or unprotected flames, including lanterns. Large fires (such as bonfires, a blacksmith's coals, or even a house fire) have a 50% chance to be extinguished by the <em>boreal wind</em>. Forest or grassland fires are too large to be extinguished by this spell.</p><p>All creatures caught in the area take 1d4 points of cold damage per caster level (maximum 15d4). A successful Fortitude saving throw negates the gust's effects. Those that fail the save are pushed away from the caster a distance of 3 feet per caster level. Creatures that remain in the area past the first round must make an additional saving throw each round.</p><p>A <em>boreal wind</em> can do anything a sudden blast of wind would be expected to do. It can create a stinging spray of sand or dust, overturn tents and blow down small huts, scuttle a small boat, and blow gases and vapors to the edge of the range.</p><p>The wind can change direction if you actively direct it (a move action for you); otherwise, it merely blows in the same direction.</p>",
    null,null,null),
    
    (731,5,"Brumal Stiffening","Transmutation",null,"Cold","V, S",
    "1 standard action","Close",null,"One weapon","1 round/level",
    "Reflex negates","Yes",
    "Brittle weapon's hardness reduced by 5.",
    "<p>The targeted weapon becomes brittle, reducing its hardness by 5 for the duration of the spell, thereby increasing the effectiveness of sunder attempts against the weapon. In addition, rolling a 1 on an attack with the targeted weapon causes it to take damage equivalent to the amount it would have dealt on a successful hit.</p>",
    null,null,null),
    
    (732,5,"Call Avalanche","Evocation",null,"Cold","V, S",
    "1 round","Long","10 ft.-radius/level spread",null,"Instantaneous",
    "Reflex half; see text","No",
    "Avalanche of ice and snow falls from the sky, burying subjects.",
    "<p>This spell may only be cast outside. Immediately upon completion of the spell, an avalanche of ice and snow falls out of the sky, dealing 8d6 points of crushing damage and potentially burying Large or smaller creatures within the area. Creatures making their Reflex saving throws take half and are not buried. Those that fail their saves are buried and take an additional 1d6 points of nonlethal damage per minute while still buried. If such a creature falls unconscious while buried, it must make a DC 15 Constitution check. If that check fails, it takes 1d6 points of lethal damage each minute thereafter until freed or dead.</p><p>The ice and snow remains until melted by natural or unnatural means. A rapid melting of the ice and snow could cause a flash flood (see Freezing and Thawing, page 10 of <em>Frostburn</em>).</p><p>A 9th-level caster buries Large or smaller creatures. At 12th level, the maximum size of a creature increases to Huge. At 15th, Gargantuan creatures are also buried, and at 18th level, a creature of up to Colossal size is buried by the snow.</p>",
    null,null,null),
    
    (733,5,"Column of Ice","Conjuration","Creation","Cold","V, S, M",
    "1 standard action","Close","One column of ice, 10-ft. radius and 5 ft./level in height",null,"Permanent",
    "Reflex negates","No",
    "Column of ice erupts from ground, lifting anything in its area into the air.",
    "<p>A column of ice rises from the ground, lifting any object or creature (including you) standing in the area into the air. Creatures making a Reflex saving throw can choose to avoid the column. Moving or fighting atop the ice column requires a DC 10 Balance check. Those who fail fall prone and must immediately succeed on a DC 12 Reflex saving throw or slip off the column, taking commensurate falling damage.</p><p>Creatures atop the column as it rises may be smashed against the ceiling or other overhead obstructions, which deals 4d6 points of damage.</p><p><strong>Magical Ice Column:</strong> 10 feet thick; hardness 16; hp 160; break DC 90; Climb DC 30.</p>",
    "Arcane Material Component: A 2-inch rod of ice.",
    null,null),
    
    (734,5,"Cometstrike","Conjuration","Creation","Cold","V, DF",
    "1 standard action","Medium",null,"Three different creatures or objects","3 rounds",
    "Reflex partial","No",
    "Three comets per round strike targets, each dealing 3d6 bludgeoning damage and 1d4/level cold damage.",
    "<p>This spell may only be cast in an outdoor area; it fails if cast indoors or underground. When you cast this spell, you cause three frozen comets to strike down upon any three different creatures or objects in range. You must make a ranged touch attack to hit each target. Each target struck takes 3d6 points of bludgeoning damage and 1d4 points of cold damage per level (maximum 10d4), and is stunned for one round. A successful Reflex save negates the bludgeoning damage and the stunning effects, but not the cold damage. Each round the spell persists, another three frozen comets rain down upon the original three targets; as a standard action, you can select new targets for one, two, or all three comets.</p>",
    null,null,null),
    
    (735,5,"Conjure Ice Beast I","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One conjured ice creature",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell creates a creature constructed from magical ice. It appears where you designate and acts immediately, on your turn. It attacks your opponents to the best of its ability. If you can communicate with the creature, you can direct it not to attack, to attack particular enemies, or to perform other actions.</p><p>The spell conjures one of the creatures from the 1st-level list of either the <em>summon monster</em> table or the <em>summon nature's ally</em> table (pages 287-288 of the <em>Player's Handbook</em>). The conjured creature cannot have the fire subtype. You choose which kind of creature to conjure, and you can change that choice each time you cast the spell. The conjured creature is a construct made of magical ice, gaining the ice beast template (see page 138 of <em>Frostburn</em>).</p><p>In all other ways, <em>conjure ice beast I</em> functions like <em>summon monster I</em>.</p>",
    null,null,null),
    
    (736,5,"Conjure Ice Beast II","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 2nd-level list or two creatures of the same kind from the 1st-level list.</p>",
    null,null,null),
    
    (737,5,"Conjure Ice Beast III","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 3rd-level list, two creatures of the same kind from the 2nd-level list, or four creatures of the same kind from the 1st-level list.</p>",
    null,null,null),
    
    (738,5,"Conjure Ice Beast IV","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 4th-level list, two creatures of the same kind from the 3rd-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (739,5,"Conjure Ice Beast V","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 5th-level list, two creatures of the same kind from the 4th-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (740,5,"Conjure Ice Beast VI","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 6th-level list, two creatures of the same kind from the 5th-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (741,5,"Conjure Ice Beast VII","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 7th-level list, two creatures of the same kind from the 6th-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (742,5,"Conjure Ice Beast VIII","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 8th-level list, two creatures of the same kind from the 7th-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (743,5,"Conjure Ice Beast IX","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 9th-level list, two creatures of the same kind from the 8th-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (744,5,"Conjure Ice Object","Conjuration","Creation","Cold","V, S, DF",
    "1 standard action","Personal","One object of up to 5 lb./level",null,"1 min./level",
    "None (harmless)","No",
    "Conjures an object made of ice.",
    "<p>You conjure into being a block of transparent ice in the shape of any object you have seen at least once before, up to the weight limit (to a maximum of 50 pounds at 10th level). Any object with moving parts does not function (for example, a crossbow). You must succeed on an appropriate Craft check to make a complex item.</p>",
    null,null,null),
    
    (745,5,"Control Snow and Ice","Transmutation",null,null,"V, S, DF",
    "1 standard action","Long","Ice and snow in a volume of 10 ft./level by 10 ft./level by 2 ft./level (S)",null,"10 min./level (D)",
    "None","No",
    "Raise or lower ice or snow.",
    "<p>Depending on the version you choose, the <em>control snow and ice</em> spell raises or lowers ice or snow.</p><p><em>Lower Snow and Ice:</em> This causes snow and ice to sink away to a minimum depth of 1 inch. The depth can be lowered by up to 2 feet per caster level. The snow and ice is lowered within a squarish depression whose sides are up to 10 feet long per caster level. In extremely large and deep snow and ice fields, such as a glacier, the spell causes a crevasse that sweeps creatures downward (without dealing damage), rendering them unable to leave by normal movement for the duration of the spell. They can climb out of a crevasse, as normal with a DC 18 Climb check. When cast on ice elementals and other ice-based creatures, this spell acts as a <em>slow</em> spell. The spell has no effect on other creatures.</p><p><em>Raise Snow and Ice:</em> This causes snow and ice to rise in height, just as the <em>lower snow and ice</em> version causes it to lower. Creatures and objects on top of the snow or ice are raised along with the top level of snow.</p><p>For either version, the character may reduce one horizontal dimension by half and double the other horizontal dimension.</p>",
    null,null,null),
    
    (746,5,"Control Temperature","Transmutation",null,"Cold, Fire","V, S, M/DF",
    "1 round","20 ft./level","20 cu. ft./level emanation, centered on you",null,"1 hour/level",
    "None","No",
    "Raise or lower temperature by one band/5 levels.",
    "<p>You imbue an area with cold or fire energy, reducing or raising the temperature by one temperature band per five caster levels. Effects of the new temperature on creatures and the environment are incurred immediately (see Cold Dangers, page 8 of <em>Frostburn</em>, and Heat Dangers, page 303 of the <em>Dungeon Master's Guide</em>).</p>:",
    "Arcane Material Component: A drop of mercury",
    null,null),
    
    (747,5,"Crack Ice","Evocation",null,"Force","V, S, M",
    "1 standard action","Close","10-ft.-radius/level spread; or one ice creature","10-ft.-radius/level spread; or one ice creature","Instantaneous",
    "Fortitude half (see text)","Yes (creature only)",
    "Shatters ice structures or ice creatures.",
    "<p>You create a sudden explosive burst that shatters ice bridges, breaks up river ice, opens frozen ponds, or damages an icy creature. The ice broken covers a 10-foot radius per caster level. Ice thicker than the spell's depth is cracked and weakened, but not broken all the way through. Weakened ice is treated as one category thinner than it really is (see Table 1-2, page 11 of <em>Frostburn</em>).</p><p>Creatures dropped from a bridge, through lake or river ice, or off a glacier or iceberg take normal falling and cold water damage. Creatures on a glacier will have a crebasse open under them equal to the depth of the spell.</p><p>Targeted against an ice creature of any weight (such as an ice golem, winterspawn, or entombed), <em>crack ice</em> deals 1d6 points of damage per caster level (maximum 10d6), with a Fortitude save for half damage.</p>",
    "Material Component: A hammer carved from salt crystal (50 gp).",
    null,null),
    
    (748,5,"Crunchy Snow","Transmutation",null,"Cold","V, S, Frostfell",
    "1 standard action","Medium","One 20-ft.-by-20-ft. square of snow/level",null,"1 hour/level",
    "None","No",
    "-20 penalty on Move Silently checks in area.",
    "<p>An area of fallen snow designated by you becomes hard and crumbly, generating a loud crunch when stepped upon. Creatures take a -20 penalty on Move Silently checks when traveling through crunchy snow.</p>",
    null,null,null),
    
    (749,5,"Death Hail","Conjuration","Creation","Cold, Death","V, S, DF",
    "1 round","Medium","Cylinder (40-ft. radius, 20 ft. high)",null,"1 round/level",
    "Fortitude half","No",
    "Summons a storm of death hail.",
    "<p>You call into being an intense storm of death hail in the area you designate. Creatures in the area must succeed on a Fortitude save or take 1d2 points of Strength and Constitution damage.</p>",
    null,null,null),
    
    (750,5,"Defile Snow and Ice","Evocation",null,"Cold, Evil","V, S",
    "1 standard action","Medium","10 ft./level radius spread",null,"1 min./level",
    "None","Yes",
    "Grants undead a +4 profane bonus against turning and cold creatures SR 15 against fire spells.",
    "<p>You imbue an area of ice or fallen snow with negative energy, granting all undead within the area a +4 profane bonus against turning attempts.</p><p>In addition, all cold creatures gain spell resistance 15 against fire effects.</p>",
    null,null,null),
    
    (751,5,"Detect Fire","Divination",null,"Cold", "V, S, DF",
    "1 standard action","60 ft.",null,null,"Concentration, up to 10 min/level (D)",
    "None","No",
    "Detect fire within 60 ft.",
    "<p>This spell functions like <em>detect evil</em> (see page 218 of the <em>Player's Handbook</em>), except that it detects heat energy from normal fire, fire spells, fire magic items, clerics of fire deities, and all living beings other than those with the cold subtype. You are vulnerable to an overwhelming heat aura if you have the cold subtype.</p><p>Living beings without the fire subtype are detected with a heat aura strength of faint only, regardless of level or Hit Dice.</p>",
    null,null,null),
    
    (752,5,"Dispel Cold","Abjuration",null,"Fire","V, S, DF",
    "1 standard action","Touch",null,"You and a touched cold creature from another plane; or you and an enchantment or cold spell on a touched creature or object","1 round/level or until discharged, whichever comes first",
    "See text","See text",
    "Cancels cold spells and effects.",
    "<p>This spell functions like <em>dispel evil</em> (see page 222 of the <em>Player's Handbook</em>), except that you are surrounded by constant, blue-white cold energy, and the spell affects cold creatures and spells rather than evil ones.</p>",
    null,null,null),
    
    (753,5,"Dispel Fire","Abjuration",null,"Cold","V, S, DF",
    "1 standard action","Touch",null,"You and a touched fire creature from another plane; or you and an enchantment or fire spell on a touched creature or object","1 round/level or until discharged, whichever comes first",
    "See text","See text",
    "Cancels fire spells and effects.",
    "<p>This spell functions like <em>dispel evil</em> (see page 222 of the <em>Player's Handbook</em>), except that you are surrounded by constant red, orange, and yellow flames, and the spell affects fire creatures and spells rather than evil ones.</p>",
    null,null,null),
    
    (756,5,"Ease of Breath","Necromancy",null,"Cold","V, S, DF",
    "1 standard action","Touch",null,"Creature touched","1 hour/level",
    "None","No",
    "+20 inherent bonus on Fortitude saves to resist altitude sickness.",
    "<p>You grant the target the ability to survive in thin air, conferring a +20 inherent bonus on Fortitude saves to resist altitude sickness as well as saving throws to resist becoming fatigued due to altitude or thin air.</p>",
    null,null,null),
    
    (757,5,"Entomb","Evocation",null,"Cold","V, S, M",
    "1 standard action","Medium","One creature/level, no two of which can be more than 30 ft. apart",null,"Instantaneous and 1 round/level; see text",
    "Fortitude negates","Yes",
    "Captures subjects in blocks of ice, suffocating them.",
    "<p>An <em>entomb</em> spell traps living creatures in a block of ice, suffocating them. The spell entraps the targets with a thick layer of ice from head to toe. Those that make a successful Fortitude saving throw can shake off the ice immediately, though they still take 6d6 points of cold damage. If the creature fails its saving throw, it is held within the ice and immediately begins to suffocate per the drowning rules (see page 304 of the <em>Dungeon Master's Guide</em>). In addition, the creature takes 2d12 points of cold damage and 1 point of Constitution damage per round from contact with the ice.</p><p>Other than attempting to escape, creatures entombed can perform actions that only require mental or verbal activity.</p><p>Escaping from the ice block requires a DC 20 Strength check or the application of 20 points of fire damage.</p>",
    "Material Component: A clear gemstone with a minimum value of 500 gp.",
    null,null),
    
    (758,5,"Evergreen","Transmutation",null,"Fire","V, S, DF",
    "1 standard action","Medium","10-ft. radius",null,"1 hour/level and instantaneous; see text",
    "None","No",
    "Magical heat warms plant life, healing 1d8 damage +1/level (max. +10) and granting immunity to cold.",
    "<p>You imbue a 10-foot-radius area of plant life with a magical heat, instantly healing 1d8 points of damage +1 point per caster level (maximum +10), and granting immunity to cold for the duration of the spell. <em>Evergreen</em> affects natural plants as well as creatures with the plant subtype.</p>",
    null,null,null),
    
    (759,5,"Fimbulwinter","Transmutation",null,"Cold","V, S, XP",
    "10 minutes (see text)","1 mile/level","1 mile/level radius, centered on you",null,"4d12 weeks",
    "None","No",
    "Creates winter weather for miles around you that lasts for months.",
    "<p>You change the weather to a state of permanent winter, or strengthen winter conditions already present. It takes 10 minutes to cast the spell and an additional 10 minutes for the effects to manifest themselves. The current natural weather conditions are determined by the DM. You then choose what wintry conditions you want to manifest; the strength of the winter depends on the eisting climate and season of the area.</p><p><table><thead><tr><th><strong>Season</strong></th><th><strong>Possible Weather</strong></th></tr></thead><tbody><tr><td>Spring</td><td>Frequent snowfall, nightly frost</td></tr><tr><td>Summer</td><td>Light snow hailstorms, cold rain, cloudy</td></tr><tr><td>Autumn</td><td>Frequest snowfall, frost</td></tr><tr><td>Winter</td><td>Frigid cold, blizzard, and constant snowfall</td></tr></tbody></table></p><p>Daily wind and snowfall during a <em>fimbulwinter</em> are determined using the table below. Add +8 to the roll when cast during winter, +4 in spring or autumn, -2 in summer, +2 for a cold climate, -2 for a temperate climate, and -6 for hot climate. Roll separately for wind and snow. The snow and wind shown are the maximum possible for the day; at your option, there can be less wind or snow.</p><p><table><thead><tr><th><strong>d20 Roll</strong></th><th><strong>Amount of Snowfall</strong></th><th><strong>Amount of Wind</strong></th></tr></thead><tbody><tr><td>0 or less</td><td>1d12 inches of snowfall melt</td><td>Weak (0-10 mph)</td></tr><tr><td>1-5</td><td>No new snow</td><td>Weak (0-10 mph)</td></tr><tr><td>6-10</td><td>1d4-1 inches snow</td><td>Moderate (11+ mph)</td></tr><tr><td>11-15</td><td>1d8 inches snow or 1 inch hail</td><td>Moderate (11+ mph)</td></tr><tr><td>16-20</td><td>1d12 inches snow</td><td>Strong (21+ mph)</td></tr><tr><td>21-25</td><td>2d12+4 inches snow</td><td>Strong (21+ mph</td></tr><tr><td>26+</td><td>1d6+1 feet of snow</td><td>Very strong (31+ mph)</td></tr></tbody></table></p><p>You control the general tendencies of the weather, such as the direction and intensity of the wind. When you select a certain weather condition to occur, the weather assumes that condition 10 minutes later (changing gradually, not abruptly). The weather continues as you left it for the duration, or until you use a standard action to designate a new kind of weather (which fully manifests itself 10 minutes later).</p>",
    null,null,"100 XP."),
    
    (760,5,"Flash-Freeze","Transmutation",null,"Earth, Cold","V, S, DF",
    "1 standard action","Close","10-ft. square/level",null,"Instantaneous",
    "None","No",
    "Earth, stone, and water becomes frozen.",
    "<p>All earth, stone, adn water in the spell's area is drained of heat. Earth, mud, and stone become everfrost and water freezes. You affect a 10-foot-square area to a depth of 1 foot. Magical, enchanted, dressed, or worked stone cannot be affected. Earth, stone, or water creatures are not affected.</p><p>This spell can be used to create small icebergs in large bodies of water. These icebergs float, but are extremely slippery and unstable, requiring a DC 15 Balance check per round to stay on the iceberg. Icebergs may be propelled through the water by the current, paddling, or other means.</p>",
    null,null,null),
    
    (761,5,"Flesh to Ice","Transmutation",null,null,"V, S, M",
    "1 standard action","Medium",null,"One creature","Instantaneous",
    "Fortitude negates","Yes",
    "Turns subject into statue of ice.",
    "The subject, along with all its carried gear, turns into a mindless, inert ice sculpture. If the sculpture resulting from this spell is broken, melted, or damaged, the subject (if ever returned to its original state) has similar damage or deformities. The ceature is not dead, but it does not seem to be alive either when viewed with spells such as <em>deathwatch</em>. Only creatures made of flesh are affected by this spell.</p>",
    "Material Component: Water and a drop of blood.",
    null,null),
    
    (762,5,"Float","Transmutation",null,null,"V, S, M",
    "1 standard action","Long",null,"One Large or smaller creature or object","1 min./level",
    "Fortitude negates","Yes",
    "Subject becomes buoyant.",
    "<p>The target gains buoyancy and can float on water for the duration of the spell. It cannot swim below the surface of the water. Creatures that must breathe water can still do so, but cannot swim under the surface. If the target is underwater at the time this spell is cast, it rises toward the surface at a speed of 30 feet.</p>",
    "Material Component: An ice cube dropped into water.",
    null,null),
    
    (763,5,"Fortify Cold Creatures","Transmutation",null,"Cold","V, S, DF",
    "1 standard action","Close","One creature/level, no two of which can be more than 30 ft. apart",null,"1 round/level",
    "None","No",
    "Cold subtype creatures gain +1 sacred bonus on attacks and saves against fire effects.",
    "<p>Creatures with the cold subtype gain a +1 sacred bonus on all attack rolls and on saving throws against fire effects.</p>",
    null,null,null),
    
    (764,5,"Freeze Armor","Transmutation",null,"Cold","V, S",
    "1 standard action","Close",null,"Metal equipment of one creature/level","1 round/level",
    "Fortitude partial; see text","Yes",
    "Locks up suits of metal armor and equipment, dealing damage and impeding movement.",
    "<p><em>Freeze armor</em> locks suits of metal armor and equipment into a layer of ice and extreme cold, immobilizing and damaging the armor's wearers. Unattended, nonmagical metal gets no saving throw. Enchanted metal is allowed a saving throw against the spell. An item in a creature's possession uses the creature's saving throw (unless its own is higher).</p><p>A creature wearing metal armor that fails its save is frozen in place. The spell locks the armor's joints and seams in inches of solid ice. The frozen creature takes the damage listed below. In addition, it suffers a -6 penalty on attack rolls, a -8 penalty to effective Dexterity, and can't move. A frozen character who attempts to cast a spell must make a Concentration check (DC 15 + the level of spell being cast) or lose the spell.</p><p>A creature wearing metal armor that makes its save takes half the damage listed below.</p><p>A creature not wearing metal armor that fails its save takes the damage listed below if its armor is affected or if it is holding, touching, wearing, or carrying metal weighing one-fifth of its weight. The creature takes minimum damage (1, 2, 3, or 4 points; see the table) each round if it is not wearing metal armor or the metal that it is carrying weighs less than one-fifth of the creature's weight.</p><p>A creature not wearing or carrying metal less than one-fifth of its weight that makes its save is entirely unaffected by <em>freeze armor</em>.</p><p><table><thead><tr><th><strong>Round</strong></th><th><strong>Temperature</strong></th><th><strong>Cold Damage</strong></th></tr></thead><tbody><tr><td>1</td><td>Cold</td><td>1d6 points</td></tr><tr><td>2</td><td>Icy</td><td>2d6 points</td></tr><tr><td>3-5</td><td>Freezing</td><td>3d6 points</td></tr><tr><td>6+</td><td>Lethal</td><td>4d6 points</td></tr></tbody></table></p><p>Any heat intense enough to damage the creature negates cold damage from the spell (and vice versa) on a point-for-point basis. For example, if the damage from a <em>freeze armor</em> spell indicates 5 points of cold damage and the creature plunges through a wall of fire in the same round and takes 8 points of fire damage, it winds up taking no cold damage and only 3 points of fire damage.</p>",
    null,null,null),
    
    (765,5,"Freezing Glance","Enchantment",null,"Cold","V, S",
    "1 standard action","Close",null,"One living creature","1 round/level; see text",
    "Will negates","Yes",
    "Gaze freezes subjects in place.",
    "<p>Your eyes become wintry tombs that destroy the spark of life in those who you meet your stare. Each round you may target a single living creature. It must make a Will saving throw or be frozen in place.</p><p>Frozen creatures cannot move, attack, cast spells, or defend themselves; they are considered immobile, losing shield and Dexterity bonuses to Armor Class and taking a further -4 penalty to Armor Class. Frozen creatures are entitled to an additional saving throw if attacked, but this provides no immunity to the gaze. A creature that has been immobilizing with a <em>freezing glance</em>, then restored to motion after an attack, can still be the target of the same <em>freezing glance</em> in a later round.</p><p>Though the gaze attack ends rather quickly, frozen creatures remain immobile for 1 minute per level. In some cases, this can cause serious damage through exposure to the elements.</p>",
    null,null,null),
    
    (766,5,"Frost Weapon","Transmutation",null,null,"V, S, M",
    "1 standard action","Touch","Weapon touched",null,"1 round/level",
    "Will negates (harmless, object)","No",
    "Weapon gains frost special ability, +1d6 cold damage.",
    "<p>You imbue a weapon with icy cold, granting it a power similar to the frost special ability. A frost weapon deals an extra 1d6 points of cold damage on a successful hit. If cast on a bow, crossbow, or sling, the spell bestows the cold energy upon the weapon's ammunition. This ability stacks with the frost special ability, but not with itself.</p>",
    "Material Component: A drop of water.",
    null,null),
    
    (767,5,"Frostbite","Conjuration","Creation","Cold","V, S, DF",
    "1 standard action","Close",null,"One creature/2 levels, no two of which can be more than 30 ft. apart","Instantaneous",
    "Fortitude half","Yes",
    "Chilled air causes 6d6 cold damage and 2d6 Dex damage.",
    "<p>You chill the air and create a layer of frost on the skin on target creatures. The targets are entitled to a Fortitude save; those who fail take 6d6 points of cold damage and 2d6 points of Dexterity damage. Creatures dropping to 0 Dexterity are frozen in a layer of ice, shivering and unable to attack, move, or defend.</p>",
    null,null,null),
    
    (768,5,"Frostburn","Necromancy",null,"Cold","V, S, DF",
    "1 standard action","Touch",null,"Creature touched","Instantaneous",
    "Fortitude half","Yes",
    "Touch deals 3d12 frostburn damage +1/level (max +20).",
    "<p>This spell functions like <em>lesser frostburn</em>, except that it deals 3d12 points of frostburn damage +1 point per caster level (maximum +20).</p><p>Lesser frostburn description included below, for convenience:</p><p>When laying your hand upon a creature, you channel cold energy that deals 1d12 points of frostburn damage +1 point per caster level (maximum +5). When cast upon a cold subtype creature, this spell heals a like amount of damage, rather than harming it.</p>",
    null,null,null),
    
    (769,5,"Frostburn, lesser","Necromancy",null,"Cold","V, S, DF",
    "1 standard action","Touch",null,"Creature touched","Instantaneous",
    "Fortitude half","Yes",
    "Touch deals 1d12 frostburn damage +1/level (max +5).",
    "<p>When laying your hand upon a creature, you channel cold energy that deals 1d12 points of frostburn damage +1 point per caster level (maximum +5). When cast upon a cold subtype creature, this spell heals a like amount of damage, rather than harming it.</p>",
    null,null,null),
    
    (770,5,"Frostburn, Mass","Necromancy",null,"Cold","V, S, DF",
    "1 standard action","Close",null,"One creature/level, no two of which can be more than 30 ft. apart","Instantaneous",
    "Fortitude half","Yes",
    "Deals 3d12 +1/level (max +20) frostburn damage to many creatures.",
    "<p>Cold energy spreads out in all directions from the point of origin, dealing 3d12 points of frostburn damage +1 point per caster level (maximum +20) to nearby enemies. Like other <em>frostburn</em> spells, <em>mass frostburn</em> cures cold subtype creatures in its area rather than damaging them.</p>",
    null,null,null);