INSERT INTO Spell
(Spell_ID, Book_ID, Spell_Name, Spell_School, Spell_Subschool,
Spell_Descriptor, Spell_Components, Spell_Casting_Time, Spell_Range,
Spell_Effect, Spell_Target, Spell_Duration, Spell_Saving_Throw,
Spell_Resistance, Spell_Short_Description, Spell_Description,
Spell_Material_Component, Spell_Focus, Spell_XP_Cost)
VALUES
    (720,5,"Algid Enhancement","Transmutation",null,"Cold","V, S, Coldfire",
    "1 round","Close",null,"One cold creature/level","24 hours",
    "None","No",
    "Grant bonuses to creatures of the cold subtype.",
    "<p>You energize cold creatures with a surge of coldfire. Creatures with the cold subtype affected by this spell gain a +1 deflection bonus to AC, +1d8 temporary hit points, a +1 enhancement bonus on attack rolls, and a +2 bonus on saving throws against fire effects. Each of these enhancements increases by +1 for every three caster levels. So a 12th-level caster grants a +5 deflection bonus to AC, an extra 1d8+4 temporary hit points, a +5 enhancement bonus on attack rolls, and a +6 resistance bonus on saving throws against fire effects.</p><p>This spell has no effect on creatures not of the cold subtype.</p>",
    "Coldfire component: One ounce of coldfire.",
    null,null),
        
    (721,5,"Animate Snow","Transmutation",null,"Cold","V, S, M",
    "1 standard action","Medium","Up to a 20-ft. cube of snow",null,"1 round/level",
    "None","No",
    "Turns snow into creatures to fight for you.",
    "<p>You imbue a mass of fallen snow with mobility and a semblance of life. The snow to be animated may be natural or magically created. Snow animated by this spell is treated as an animated object. You can animate four Large animated objects, two Huge animated objects, or one Gargantuan animated object. For details, see the Animated Object entry, page 13 of the <em>Monster Manual</em>. The animated snow can assume any basic shape you wish, and it attacks as directed by your vocal commands. Animated snow objects possess the Blind and Trample special attacks as detailed in the <em>Monster Manual</em> entry for animated objects. In addition, they have the cold subtype, and do an additional 1d6 points of cold damage on a successful hit.</p><p>Animated snow objects take 1d6 points of damage each round if they exist in a place with temperatures above freezing.</p>",
    "Material Component: Meltwater from a glacier.",
    null,null),

    (722,5,"Anticold Sphere","Abjuration",null,null,"V, S",
    "1 standard action","10 ft.","10-ft.-radius emanation, centered on you",null,"10 min./level (D)",
    "None","Yes",
    "Mobile energy field provides immunity to cold.",
    "<p>You bring into being a mobile, spherical energy field that protects against cold. All creatures within the area of the spell are granted immunity to cold. In addition, the sphere prevents the entrance of any creature with the cold subtype. The effect hedges out such creatures in the area when the spell is cast.</p><p>This spell may be used only defensively, not aggressively. Forcing an abjuration barrier against creatures that the spell keeps at bay collapses the barrier (see Abjuration, page 172 of the <em>Player's Handbook</em>).</p>",
    null,null,null),
    
    (723,5,"Arctic Haze","Conjuration","Creation","Cold","V, S",
    "1 standard action","Medium","Fog spreads in a 30-ft. radius, 20 ft. high",null,"10 min./level",
    "Fortitude half","No",
    "Fog obscures vision and deals 4 cold damage per round.",
    "<p>A bank of fog composed entirely of razor-sharp ice shards billows out from the targeted point. The fog obscures all sight, including darkvision, beyond 5 feet. A creature 5 feet away has concealment (20% miss chance). Creatures farther away have total concealment (50% miss chance, and the attacker can't use sight to locate the target).</p><p>In addition, the sharp ice particles tear the skin of those moving through the area, causing 4 points of damage per round, half of which is cold damage.</p><p>A strong wind (21+ mph) diserses the fog in 4 rounds; a severe wind (31+ mph) disperses the fog in 1 round. Dispersing the fog in this manner, however, causes damage to those within the area as the icy shards whip past. A strong wind causes 4 points of damage per round (half cold); a severe wind causes 8 points of damage (half cold).</p>",
    null,null,null),
    
    (724,5,"Aura of Cold, Greater","Transmutation",null,"Cold","V, S, DF",
    "1 standard action","10 ft.","10-ft.-radius spherical emanation, cenetered on you",null,"1 round/level (D)",
    "None","Yes",
    "Intense cold deals 2d6 damage to creatures within 10 ft.",
    "<p>This spell functions exactly like <em>lesser aura of cold</em>, except it deals 2d6 points of cold damage to all creatures within 10 feet.</p><p>Lesser aura of cold's description is added below, for convenience:</p><p>You are covered in a thin layer of white frost and frigid cold emanates from your body, dealing 1d6 points of cold damage at the start of your round to each creature within 5 feet.</p>",
    null,null,null),

    (725,5,"Aura of Cold, Lesser","Transmutation",null,"Cold","V, S, DF",
    "1 standard action","5 ft.","5-ft.-radius spherical emanation, centered on you",null,"1 round/level (D)",
    "None","Yes",
    "Intense cold deals 1d6 damage to creatures within 5 ft.",
    "<p>You are covered in a thin layer of white frost and frigid cold emanates from your body, dealing 1d6 points of cold damage at the start of your round to each creature within 5 feet.</p>",
    null,null,null),

    (726,5,"Binding Snow","Transmutation",null,"Cold","V, S, DF, Frostfell",
    "1 standard action","Medium","One 10-ft. square/level",null,"1 hour/level (D)",
    "Reflex negates","Yes",
    "Snow freezes, impeding movement",
    "<p>This spell must be cast on a snow field. That snow field instantly freezes, impeding movement through the area. A creature caught within the area can move only at half its normal speed. By making a DC 20 Strength check or a DC 25 Escape Artist check, the creature can move at its normal speed for that round. A creature that succeeds on a Reflex save is not impeded.</p>",
    null,null,null),

    (727,5,"Blizzard","Transmutation",null,"Cold","V, S",
    "1 round","Long","100 ft.-radius/level spread",null,"1 round/level",
    "Fortitude partial","No",
    "Temperature drops and powerful blizzard reduces visibility to zero.",
    "<p>Immediately upon completion of this spell, the temperature drops to below freezing and a powerful blizzard erupts in the area. Visibility is reduced to zero, making Spot, Search, and Listen checks and all ranged attacks impossible. Unprotected flames are automatically extinguished and protected flames have a 75% chance of being doused. Creatures unprotected from the cold must make a Fortitude save or take 1d6 points of nonlethal cold damage.</p><p>One foot of new snow falls each round. Movement within the area is impeded, depending on the creature's size and depth of snow (for movement in a snow field, see page 12 of <em>Frostburn</em>).</p>",
    null,null,null),
    
    (728,5,"Blood Snow","Necromancy",null,"Cold","V, S",
    "1 standard action","Medium","20-ft. square of snow/level",null,"1 round/level",
    "Fortitude negates","Yes",
    "Area of fallen snow drains 1d2 points of Con/round and causes nausea.",
    "<p>You must cast this spell on a snow field. You corrupt an area of fallen snow, imbuing it with negative energy. Each round, a creature in contact with blood snow must succeed on a Fortitude save or take 1d2 points of Constitution drain. In addition, anyone failing a saving throw is nauseated for the duration of the spell.</p>",
    null,null,null),

    (729,5,"Bone Chill","Necromancy",null,null,"V, S, M",
    "1 standard action","Close","Ray",null,"1 round/level",
    "Fortitude negates","No",
    "Corporeal undead are held by a thick layer of frost.",
    "<p>A ray of burning cold erupts from your fingertips. Corporeal undead struck by the ray are covered in a layer of ice, rendering the subject immobile as if <em>held</em>. Each round on its turn, the subject may attempt a new saving throw to break free of the ice. (This is a full-round action that does not provoke attacks of opportunity.)</p>",
    "Material Component: A small piece of bone and a 1-inch cube of ice.",
    null,null),
    
    (730,5,"Boreal Wind","Evocation",null,"Cold","V, S, DF",
    "1 standard action","Long","Gust of wind (20 ft. wide, 20 ft. high) emanating out from you to the extreme of the range",null,"1 round + 1 round/2 levels",
    "Fortitude negates","Yes",
    "Gust of cold wind deals 1d4 cold damage/level and knocks creatures back.",
    "<p>You create a strong blast of arctic air that originates from your fingertips and moves in the direction you are facing. As a stronger form of <em>gust of wind</em>, this boreal wind automatically extinguishes candles, torches, and similar protected or unprotected flames, including lanterns. Large fires (such as bonfires, a blacksmith's coals, or even a house fire) have a 50% chance to be extinguished by the <em>boreal wind</em>. Forest or grassland fires are too large to be extinguished by this spell.</p><p>All creatures caught in the area take 1d4 points of cold damage per caster level (maximum 15d4). A successful Fortitude saving throw negates the gust's effects. Those that fail the save are pushed away from the caster a distance of 3 feet per caster level. Creatures that remain in the area past the first round must make an additional saving throw each round.</p><p>A <em>boreal wind</em> can do anything a sudden blast of wind would be expected to do. It can create a stinging spray of sand or dust, overturn tents and blow down small huts, scuttle a small boat, and blow gases and vapors to the edge of the range.</p><p>The wind can change direction if you actively direct it (a move action for you); otherwise, it merely blows in the same direction.</p>",
    null,null,null),
    
    (731,5,"Brumal Stiffening","Transmutation",null,"Cold","V, S",
    "1 standard action","Close",null,"One weapon","1 round/level",
    "Reflex negates","Yes",
    "Brittle weapon's hardness reduced by 5.",
    "<p>The targeted weapon becomes brittle, reducing its hardness by 5 for the duration of the spell, thereby increasing the effectiveness of sunder attempts against the weapon. In addition, rolling a 1 on an attack with the targeted weapon causes it to take damage equivalent to the amount it would have dealt on a successful hit.</p>",
    null,null,null),
    
    (732,5,"Call Avalanche","Evocation",null,"Cold","V, S",
    "1 round","Long","10 ft.-radius/level spread",null,"Instantaneous",
    "Reflex half; see text","No",
    "Avalanche of ice and snow falls from the sky, burying subjects.",
    "<p>This spell may only be cast outside. Immediately upon completion of the spell, an avalanche of ice and snow falls out of the sky, dealing 8d6 points of crushing damage and potentially burying Large or smaller creatures within the area. Creatures making their Reflex saving throws take half and are not buried. Those that fail their saves are buried and take an additional 1d6 points of nonlethal damage per minute while still buried. If such a creature falls unconscious while buried, it must make a DC 15 Constitution check. If that check fails, it takes 1d6 points of lethal damage each minute thereafter until freed or dead.</p><p>The ice and snow remains until melted by natural or unnatural means. A rapid melting of the ice and snow could cause a flash flood (see Freezing and Thawing, page 10 of <em>Frostburn</em>).</p><p>A 9th-level caster buries Large or smaller creatures. At 12th level, the maximum size of a creature increases to Huge. At 15th, Gargantuan creatures are also buried, and at 18th level, a creature of up to Colossal size is buried by the snow.</p>",
    null,null,null),
    
    (733,5,"Column of Ice","Conjuration","Creation","Cold","V, S, M",
    "1 standard action","Close","One column of ice, 10-ft. radius and 5 ft./level in height",null,"Permanent",
    "Reflex negates","No",
    "Column of ice erupts from ground, lifting anything in its area into the air.",
    "<p>A column of ice rises from the ground, lifting any object or creature (including you) standing in the area into the air. Creatures making a Reflex saving throw can choose to avoid the column. Moving or fighting atop the ice column requires a DC 10 Balance check. Those who fail fall prone and must immediately succeed on a DC 12 Reflex saving throw or slip off the column, taking commensurate falling damage.</p><p>Creatures atop the column as it rises may be smashed against the ceiling or other overhead obstructions, which deals 4d6 points of damage.</p><p><strong>Magical Ice Column:</strong> 10 feet thick; hardness 16; hp 160; break DC 90; Climb DC 30.</p>",
    "Arcane Material Component: A 2-inch rod of ice.",
    null,null),
    
    (734,5,"Cometstrike","Conjuration","Creation","Cold","V, DF",
    "1 standard action","Medium",null,"Three different creatures or objects","3 rounds",
    "Reflex partial","No",
    "Three comets per round strike targets, each dealing 3d6 bludgeoning damage and 1d4/level cold damage.",
    "<p>This spell may only be cast in an outdoor area; it fails if cast indoors or underground. When you cast this spell, you cause three frozen comets to strike down upon any three different creatures or objects in range. You must make a ranged touch attack to hit each target. Each target struck takes 3d6 points of bludgeoning damage and 1d4 points of cold damage per level (maximum 10d4), and is stunned for one round. A successful Reflex save negates the bludgeoning damage and the stunning effects, but not the cold damage. Each round the spell persists, another three frozen comets rain down upon the original three targets; as a standard action, you can select new targets for one, two, or all three comets.</p>",
    null,null,null),
    
    (735,5,"Conjure Ice Beast I","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One conjured ice creature",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell creates a creature constructed from magical ice. It appears where you designate and acts immediately, on your turn. It attacks your opponents to the best of its ability. If you can communicate with the creature, you can direct it not to attack, to attack particular enemies, or to perform other actions.</p><p>The spell conjures one of the creatures from the 1st-level list of either the <em>summon monster</em> table or the <em>summon nature's ally</em> table (pages 287-288 of the <em>Player's Handbook</em>). The conjured creature cannot have the fire subtype. You choose which kind of creature to conjure, and you can change that choice each time you cast the spell. The conjured creature is a construct made of magical ice, gaining the ice beast template (see page 138 of <em>Frostburn</em>).</p><p>In all other ways, <em>conjure ice beast I</em> functions like <em>summon monster I</em>.</p>",
    null,null,null),
    
    (736,5,"Conjure Ice Beast II","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 2nd-level list or two creatures of the same kind from the 1st-level list.</p>",
    null,null,null),
    
    (737,5,"Conjure Ice Beast III","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 3rd-level list, two creatures of the same kind from the 2nd-level list, or four creatures of the same kind from the 1st-level list.</p>",
    null,null,null),
    
    (738,5,"Conjure Ice Beast IV","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 4th-level list, two creatures of the same kind from the 3rd-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (739,5,"Conjure Ice Beast V","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 5th-level list, two creatures of the same kind from the 4th-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (740,5,"Conjure Ice Beast VI","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 6th-level list, two creatures of the same kind from the 5th-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (741,5,"Conjure Ice Beast VII","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 7th-level list, two creatures of the same kind from the 6th-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (742,5,"Conjure Ice Beast VIII","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 8th-level list, two creatures of the same kind from the 7th-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (743,5,"Conjure Ice Beast IX","Conjuration","Creation","Cold","V, S, DF",
    "1 round","Close","One or more conjured ice creatures, no two of which can be more than 30 ft. apart",null,"1 round/level (D)",
    "None","No",
    "Conjures ice creature to fight for you.",
    "<p>This spell functions like <em>conjure ice beast I</em>, except that you can conjure one creature from the 9th-level list, two creatures of the same kind from the 8th-level list, or four creatures of the same kind from a lower-level list.</p>",
    null,null,null),
    
    (744,5,"Conjure Ice Object","Conjuration","Creation","Cold","V, S, DF",
    "1 standard action","Personal","One object of up to 5 lb./level",null,"1 min./level",
    "None (harmless)","No",
    "Conjures an object made of ice.",
    "<p>You conjure into being a block of transparent ice in the shape of any object you have seen at least once before, up to the weight limit (to a maximum of 50 pounds at 10th level). Any object with moving parts does not function (for example, a crossbow). You must succeed on an appropriate Craft check to make a complex item.</p>",
    null,null,null),
    
    (745,5,"Control Snow and Ice","Transmutation",null,null,"V, S, DF",
    "1 standard action","Long","Ice and snow in a volume of 10 ft./level by 10 ft./level by 2 ft./level (S)",null,"10 min./level (D)",
    "None","No",
    "Raise or lower ice or snow.",
    "<p>Depending on the version you choose, the <em>control snow and ice</em> spell raises or lowers ice or snow.</p><p><em>Lower Snow and Ice:</em> This causes snow and ice to sink away to a minimum depth of 1 inch. The depth can be lowered by up to 2 feet per caster level. The snow and ice is lowered within a squarish depression whose sides are up to 10 feet long per caster level. In extremely large and deep snow and ice fields, such as a glacier, the spell causes a crevasse that sweeps creatures downward (without dealing damage), rendering them unable to leave by normal movement for the duration of the spell. They can climb out of a crevasse, as normal with a DC 18 Climb check. When cast on ice elementals and other ice-based creatures, this spell acts as a <em>slow</em> spell. The spell has no effect on other creatures.</p><p><em>Raise Snow and Ice:</em> This causes snow and ice to rise in height, just as the <em>lower snow and ice</em> version causes it to lower. Creatures and objects on top of the snow or ice are raised along with the top level of snow.</p><p>For either version, the character may reduce one horizontal dimension by half and double the other horizontal dimension.</p>",
    null,null,null),
    
    (746,5,"Control Temperature","Transmutation",null,"Cold, Fire","V, S, M/DF",
    "1 round","20 ft./level","20 cu. ft./level emanation, centered on you",null,"1 hour/level",
    "None","No",
    "Raise or lower temperature by one band/5 levels.",
    "<p>You imbue an area with cold or fire energy, reducing or raising the temperature by one temperature band per five caster levels. Effects of the new temperature on creatures and the environment are incurred immediately (see Cold Dangers, page 8 of <em>Frostburn</em>, and Heat Dangers, page 303 of the <em>Dungeon Master's Guide</em>).</p>:",
    "Arcane Material Component: A drop of mercury",
    null,null);