INSERT INTO Spell
(Spell_ID, Book_ID, Spell_Name, Spell_School, Spell_Subschool,
Spell_Descriptor, Spell_Components, Spell_Casting_Time, Spell_Range,
Spell_Effect, Spell_Target, Spell_Duration, Spell_Saving_Throw,
Spell_Resistance, Spell_Short_Description, Spell_Description,
Spell_Material_Component, Spell_Focus, Spell_XP_Cost)
VALUES
    (720,5,"Algid Enhancement","Transmutation",null,"Cold","V, S, Coldfire",
    "1 round","Close",null,"One cold creature/level","24 hours",
    "None","No",
    "Grant bonuses to creatures of the cold subtype.",
    "<p>You energize cold creatures with a surge of coldfire. Creatures with the cold subtype affected by this spell gain a +1 deflection bonus to AC, +1d8 temporary hit points, a +1 enhancement bonus on attack rolls, and a +2 bonus on saving throws against fire effects. Each of these enhancements increases by +1 for every three caster levels. So a 12th-level caster grants a +5 deflection bonus to AC, an extra 1d8+4 temporary hit points, a +5 enhancement bonus on attack rolls, and a +6 resistance bonus on saving throws against fire effects.</p><p>This spell has no effect on creatures not of the cold subtype.</p>",
    "Coldfire component: One ounce of coldfire.",
    null,null),
        
    (721,5,"Animate Snow","Transmutation",null,"Cold","V, S, M",
    "1 standard action","Medium","Up to a 20-ft. cube of snow",null,"1 round/level",
    "None","No",
    "Turns snow into creatures to fight for you.",
    "<p>You imbue a mass of fallen snow with mobility and a semblance of life. The snow to be animated may be natural or magically created. Snow animated by this spell is treated as an animated object. You can animate four Large animated objects, two Huge animated objects, or one Gargantuan animated object. For details, see the Animated Object entry, page 13 of the <em>Monster Manual</em>. The animated snow can assume any basic shape you wish, and it attacks as directed by your vocal commands. Animated snow objects possess the Blind and Trample special attacks as detailed in the <em>Monster Manual</em> entry for animated objects. In addition, they have the cold subtype, and do an additional 1d6 points of cold damage on a successful hit.</p><p>Animated snow objects take 1d6 points of damage each round if they exist in a place with temperatures above freezing.</p>",
    "Material Component: Meltwater from a glacier.",
    null,null),

    (722,5,"Anticold Sphere","Abjuration",null,null,"V, S",
    "1 standard action","10 ft.","10-ft.-radius emanation, centered on you",null,"10 min./level (D)",
    "None","Yes",
    "Mobile energy field provides immunity to cold.",
    "<p>You bring into being a mobile, spherical energy field that protects against cold. All creatures within the area of the spell are granted immunity to cold. In addition, the sphere prevents the entrance of any creature with the cold subtype. The effect hedges out such creatures in the area when the spell is cast.</p><p>This spell may be used only defensively, not aggressively. Forcing an abjuration barrier against creatures that the spell keeps at bay collapses the barrier (see Abjuration, page 172 of the <em>Player's Handbook</em>).</p>",
    null,null,null),
    
    (723,5,"Arctic Haze","Conjuration","Creation","Cold","V, S",
    "1 standard action","Medium","Fog spreads in a 30-ft. radius, 20 ft. high",null,"10 min./level",
    "Fortitude half","No",
    "Fog obscures vision and deals 4 cold damage per round.",
    "<p>A bank of fog composed entirely of razor-sharp ice shards billows out from the targeted point. The fog obscures all sight, including darkvision, beyond 5 feet. A creature 5 feet away has concealment (20% miss chance). Creatures farther away have total concealment (50% miss chance, and the attacker can't use sight to locate the target).</p><p>In addition, the sharp ice particles tear the skin of those moving through the area, causing 4 points of damage per round, half of which is cold damage.</p><p>A strong wind (21+ mph) diserses the fog in 4 rounds; a severe wind (31+ mph) disperses the fog in 1 round. Dispersing the fog in this manner, however, causes damage to those within the area as the icy shards whip past. A strong wind causes 4 points of damage per round (half cold); a severe wind causes 8 points of damage (half cold).</p>",
    null,null,null),
    
    (724,5,"Aura of Cold, Greater","Transmutation",null,"Cold","V, S, DF",
    "1 standard action","10 ft.","10-ft.-radius spherical emanation, cenetered on you",null,"1 round/level (D)",
    "None","Yes",
    "Intense cold deals 2d6 damage to creatures within 10 ft.",
    "<p>This spell functions exactly like <em>lesser aura of cold</em>, except it deals 2d6 points of cold damage to all creatures within 10 feet.</p><p>Lesser aura of cold's description is added below, for convenience:</p><p>You are covered in a thin layer of white frost and frigid cold emanates from your body, dealing 1d6 points of cold damage at the start of your round to each creature within 5 feet.</p>",
    null,null,null),

    (725,5,"Aura of Cold, Lesser","Transmutation",null,"Cold","V, S, DF",
    "1 standard action","5 ft.","5-ft.-radius spherical emanation, centered on you",null,"1 round/level (D)",
    "None","Yes",
    "Intense cold deals 1d6 damage to creatures within 5 ft.",
    "<p>You are covered in a thin layer of white frost and frigid cold emanates from your body, dealing 1d6 points of cold damage at the start of your round to each creature within 5 feet.</p>",
    null,null,null),

    (726,5,"Binding Snow","Transmutation",null,"Cold","V, S, DF, Frostfell",
    "1 standard action","Medium","One 10-ft. square/level",null,"1 hour/level (D)",
    "Reflex negates","Yes",
    "Snow freezes, impeding movement",
    "<p>This spell must be cast on a snow field. That snow field instantly freezes, impeding movement through the area. A creature caught within the area can move only at half its normal speed. By making a DC 20 Strength check or a DC 25 Escape Artist check, the creature can move at its normal speed for that round. A creature that succeeds on a Reflex save is not impeded.</p>",
    null,null,null),

    (727,5,"Blizzard","Transmutation",null,"Cold","V, S",
    "1 round","Long","100 ft.-radius/level spread",null,"1 round/level",
    "Fortitude partial","No",
    "Temperature drops and powerful blizzard reduces visibility to zero.",
    "<p>Immediately upon completion of this spell, the temperature drops to below freezing and a powerful blizzard erupts in the area. Visibility is reduced to zero, making Spot, Search, and Listen checks and all ranged attacks impossible. Unprotected flames are automatically extinguished and protected flames have a 75% chance of being doused. Creatures unprotected from the cold must make a Fortitude save or take 1d6 points of nonlethal cold damage.</p><p>One foot of new snow falls each round. Movement within the area is impeded, depending on the creature's size and depth of snow (for movement in a snow field, see page 12 of <em>Frostburn</em>).</p>",
    null,null,null),
    
    (728,5,"Blood Snow","Necromancy",null,"Cold","V, S",
    "1 standard action","Medium","20-ft. square of snow/level",null,"1 round/level",
    "Fortitude negates","Yes",
    "Area of fallen snow drains 1d2 points of Con/round and causes nausea.",
    "<p>You must cast this spell on a snow field. You corrupt an area of fallen snow, imbuing it with negative energy. Each round, a creature in contact with blood snow must succeed on a Fortitude save or take 1d2 points of Constitution drain. In addition, anyone failing a saving throw is nauseated for the duration of the spell.</p>",
    null,null,null),

    (729,5,"Bone Chill","Necromancy",null,null,"V, S, M",
    "1 standard action","Close","Ray",null,"1 round/level",
    "Fortitude negates","No",
    "Corporeal undead are held by a thick layer of frost.",
    "<p>A ray of burning cold erupts from your fingertips. Corporeal undead struck by the ray are covered in a layer of ice, rendering the subject immobile as if <em>held</em>. Each round on its turn, the subject may attempt a new saving throw to break free of the ice. (This is a full-round action that does not provoke attacks of opportunity.)</p>",
    "Material Component: A small piece of bone and a 1-inch cube of ice.",
    null,null);