
INSERT INTO Misc_Item (Misc_Item_ID,Book_ID,Misc_Item_Name,Misc_Item_Type,Misc_Item_Cost,Misc_Item_Weight,Misc_Item_Description)
VALUES
    (135,4,"Distillation Kit","Adventuring Gear",50.00,20.00,
    "<p>Water is precious in the waste. This simple kit uses the sun and ambient heat to evaporate pure water from body or cooking waste, salt lakes, poisonous plant saps, and so on. This 'solar still' consists of a sheet of glass fastened at an angle into a frame, with a lip and a small spout (the components are packed separately and assembled when needed). The bottom and sides of the frame are covered with black oilcloth, the edges sealed with grease or tar to make it watertight. To use the still, pour the dirty water on the into the bottom of the container, then place the glass lid on top. The water evaporates and condenses on the underside of the glass surface, where it runs down and collects in the lip, dripping through the spout and producing about 1 gallon of water er day (if the container is filled to capacity).</p>"),
    
    (136,4,"Drill","Adventuring Gear",5.00,7.00,
    "<p>Whether they are used to carve sandstone, locate water, or mine salt and other precious minerals, drills are important tools in any wasteland environment. These objects can range from a primitive bow drill, suitable for perforating bone and wood, to a massive assembly of cast-iron pipes and bits, turned by wheels or beasts of burden. The drill described here is made of iron with a wooden handle, about 3 feet long. (In metal-poor areas, the bit might be of hard crystal instead of iron.) Wrapping a cord about the shaft and pulling it sharply sets the drill spinning. It can penetrate roughly 6 inches of stone per hour; the rate of drilling is faster in softer material, such as salt. A drill can be used as an improvised club or shortspear.</p>"),
    
    (137,4,"Filter Mask","Adventuring Gear",1.00,null,
    "<p>A filter mask is a fine cloth mesh, usually of silk or cotton, that covers your mouth and nose. Cords or straps fasten the cloth around the back of your head to provide a good seal. A filter mask grants a +2 bonus on saves against gas-based effects. It negates the effects of suffocation from dust and sand, as well as the effects of supernatural or magic dust (such as slumber sand) for up to 4 hours. After this time, the mesh is clogged with grit and can no longer allow air to pass through freely. A clogged filter mask requires thorough laundering before it can be reused, but most travelers simply replace it with fresh fabric.</p>"),
    
    (138,4,"Parasol","Adventuring Gear",3.00,2.00,
    "<p>The simplest form of portable shade, a parasol can range from an animal hide draped over a crude framework to a collapsible construction of textile and metal. The typical parasol described here is made of stretched canvas over wood or bone. A parasol offers immunity to sun glare and limited protection from heat dangers and some sun hazards (see chapter 1 of <em>Sandstorm</em>). It also grants a +1 bonus on Fortitude saves against dehydration.</p>"),
    
    (139,4,"Sand Tube","Adventuring Gear",80.00,5.00,
    "<p>When a storm scours the land, the best defense is to escape. Burrowing into the ground is one way to do this, but sand is loose and difficult to stabilize. This handy device enables you to create a burrow beneath the sand, in which you can rest while waiting for the storm to pass.</p><p>A sand tube looks something like an open-ended sleeping bag, made of treated hide attached to a number of collapsible hoops. After digging a small hole in the sand to get started, you shove one end of this apparatus inside the hole and expand the hoops to stiffen it into a tube. More sand can then be dug from the buried end (usually you crawl partway into the tube and use your hands) and removed through the tube, which is shoved more deeply into the tunnel as digging progresses. In normal sand, it takes 10 minutes of digging to fully bury a sand tube. When fully buried, a sand tube can hold one Medium humanoid. A flap fastens over the exposed end to provide shade and protection from duststorms and sandstorms.</p>"),
    
    (140,4,"Sun Lenses","Adventuring Gear",10.00,null,
    "<p>This item, made of thin slabs of mica or volcanic glass affixed to curved frames, can protect your eyes from being dazzled by bright light, such as glare (see page 18 of <em>Sandstorm</em>). If you are already dazzled when you don the lenses, you are treated as if you had entered an area of shade; you recover from the dazzled condition in 1 hour if you continue to wear the lenses.</p>"),
    
    (141,4,"Desert Outfit","Clothing",6.00,3.00,
    "<p>This outfit consists of loose, billowy clothing to keep the wearer cool and protected from the sun while in hot, dry desert terrain. It includes a caftan, turban, scarf, loose pantaloons, and sandals or high cloth boots. This outfit counts as light clothing and offers limited protections against some waste hazards (see Chapter 1 of <em>Sandstorm</em>). The protection it offers against heat is negated if the wearer also dons armor.</p>"),
    
    (142,4,"Heatsuit Outfit","Clothing",20.00,15.00,
    "<p>This suit is designed to protect against heat. It consists of heavy pants and coat, a specially treated leather apron, thick mittens, a thick hood, and goggles. A heatsuit outfit prevents 3 points of lethal or nonlethal damage per round from hot environments. Although the outfit is heavy clothing, its heat-resistant materials negate the usual -4 penalty on Fortitude saves against damage dealt by hot environments.</p>"),
    
    (143,4,"Hydration Suit","Clothing",1000.00,10.00,
    "<p>The hydration suit is a masterpiece of water retention, crafted by waste-dwellers with technical skill and unusual materials. Its design allows you to recover nearly all the water your body loses through sweat and exhalation. A hydration suit is made of the skin and issue of various desert-dwelling beasts and treated with oils or waxes for water retention. It covers your entire body, with a tight-fitting hood over the head and a mask covering the mouth and nose. Inside the mask is a glass plate to collect condensation and a tube fashioned from watertight materials. An inner lining wicks sweat away from your body and collects it in a spongelike filtration material that can be removed after you doff the hydration suit. The tube from the facemask twists in loops around your body, through the sponge, to reclaim moisture, condesnsing it in a reservoir from which you can sip.</p><p>A functioning hydration suit eliminates the need to make Constitution checks to avoid dehydration. It raises the level of protection from heat dangers by two steps (see page 14 of <em>Sandstorm</em>), and its mask functions as a filter mask. A hydration suit offers no protection from magical dessication damage.</p>"),
    
    (144,4,"Armorbright (flask)","Special Substances and Items",50.00,1.00,
    "<p>This metallic paint is applied with a brush to the outside of a suit of armor (requiring 1 minute to apply), producing a shiny surface that reflects the light of the sun to reduce the effects of hot weather on the wearer. For 24 hours after applying armorbright to a suit of armor, you gain a +2 bonus on Fortitude saving throws to avoid heat dangers. Armorbright also raises your level of protection against heat by one step (see page 14 of <em>Sandstorm</em>). Armorbright is not effective in hot environments with no sun, such as the Elemental Plane of Fire.</p>"),
    
    (145,4,"Blackeye (vial)","Special Substances and Items",1.00,0.50,
    "<p>This oily paint is smeared around your eyes and on your cheeks to reduce the effects of bright sun, protecting you from sun glare for 4 hours.</p>"),
    
    (146,4,"Deep Draught","Special Substances and Items",10.00,0.50,
    "<p>This powder is a mixture of salt, dried herbs, and extracts of desert plants. Adding it to water increases your body's retention of fluid and helps counteract the effects of dehydration. One packet of deep draught is enough for 1 gallon of solution, which grants a +5 bonus on Heal checks to treat dehydration (see page 15 of <em>Sandstorm</em>).</p>"),
    
    (147,4,"Ironthorn Extract (flask)","Special Substances and Items",25.00,1.00,
    "<p>The ironthorn plant has extremely tough tissues to prevent water loss. This extract of the plant is used to harden delicate items, make containers waterproof, and stiffen clothing to provide some protection. One flask of ironthorn extract is enough to treat a typical outfit, increasing the clothing's armor bonus to +1. Ironthorn extract does not improve materials that already provide an armor bonus. When applied to cloth, leather, or similar material, ironthorn extract improves its hardness by 1, to a maximum of 5. Both benefits last for one week or until the item is thoroughly washed.</p>"),
    
    (148,4,"Keepcool Salve (pot)","Special Substances and Items",50.00,0.50,
    "<p>This small clay pot contains several ounces of a pearly ointment, enough to cover one Medium creature. Applying the ointment to your skin increases your level of protection against heat by one step (see page 14 of <em>Sandstorm</em>). The salve also grants a +1 circumstance bonus on Fortitude saves to resist damage from hot environments.</p>"),
    
    (149,4,"Liquid Salt (flask)","Special Substances and Items",200.00,1.00,
    "<p>This deadly supernatural substance (see Red Seas, page 25 of <em>Sandstorm</em>) can be used as a splash weapon. A direct hit deals 2d6 points of dessication damage (2d8 points to plants or elementals with the water subtype). Every creature within 5 feet of the point where the flask hits takes 1d4 points of dessication damage from the splash (1d6 points to plants or elementals with the water subtype). Liquid salt is always carried in a glass container.</p>"),
    
    (150,4,"Oleum (flask)","Special Substances and Items",30.00,1.00,
    "<p>A black liquid, oleum has a foul, bitter odor. It occurs normally around the world, but is particularly common in the waste. Though it forms underground, oleum is generally found in surface pools in areas of barren waste terrain.</p><p>You can use a flask of oleum as a splash weapon. Use the rules for alchemist's fire (page 128 of the <em>Player's Handbook</em>), except that it takes a full-round action to prepare a flask with a fuse. Once it is thrown, there is a 50% chance of the flask igniting successfully. Buning oleum is hard to put out, granting a -4 penalty on the Reflex save to extinguish the fire. The oleum burns away within 4 rounds (eliminating the penalty on putting out the fire).</p><p>Raw oleum burns readily, but it is smoky when it does so. The smoke created by burning oleum is heavy smoke (see Smoke, page 304 of the <em>Dungeon Master's Guide</em>), so a wide area of open air is required for the substance to burn safely. Every round when raw oleum burns, it produces enough smoke to fill a 5-foot cube. For this reason, oleum is typically used in lamps made to burn outdoors. The smoke drives away flying insects.</p><p>Oleum is also used to lubricate moving parts; a flask of it can cover a 5-foot square, provided that the surface is smooth. A creature can walk within or through an area of oleum at half normal speed by making a DC 10 Balance check. Failure means it can't move that round, while failing by 5 or more means it falls prone (see the Balance skill description, page 67 of the <em>Player's Handbook</em>, for details). If an area of oleum is ignited, it burns for 4 rounds and deals 1d3 points of fire damage to each creature in the area.</p><p>A quart of oleum (two flasks) can coat a Medium creature, providing a +4 circumstance bonus on Escape Artist checks and opposed grapple checks made to resist being grappled or to escape a pin. Oleum applied in this manner also acts as insect repellent, protecting you from normal vermin (such as those summoned by <em>insect plague</em>) and granting a +4 bonus to Armor Class against vermin. A creature with oleum on its hands takes a -4 penalty on grapple checks or any task requiring a solid grip, including attack rolls with weapons. A roll of 1 on the attack means the oleum-coated creature drops the slippery weapon.</p><p>When worn, oleum is uncomfortable and unpleasant. You take a -2 penalty on Fortitude saves against natural heat effects. Further, oleum makes you quite flammable, granting a -4 penalty on saves against supernaturally hot effects and any attack involving fire, including Reflex saves to put yourself out after catching fire. When subjected to a fire-based attack that does not normally cause subjects to catch on fire, you must make a DC 14 Reflex save or catch on fire. As indicated above, oleum burns away after 4 rounds.</p><p>An ounce of oleum can substitute for the material component usually used for a <em>grease</em> spell.</p>"),
    
    (151,4,"Shapesand (jug)","Special Substances and Items",100.00,12.00,
    "<p>Shapesand is a special kind of wasteland soil that is psychoreactive; it can be sculpted into any form according to your will. The new object is made of sand, but serves as a normal item of the same sort. A shapesand hammer functions just like an ordinary hammer, and shapesand waterskin is just as watertight as an ordinary skin.</p><p>Controlling shapesand is an exercise in willpower. A DC 16 Wisdom check establishes control of a volume of sand based on the shaper's Wisdom score:</p><table><thead></thead><tr><th><strong>Wisdom Score</strong></th><th><strong>Controllable Volume</strong></th></tr><tbody><tr><td>1-3</td><td>None</td></tr><tr><td>4-7</td><td>1-ft. cube</td></tr><tr><td>8-11</td><td>2-1/2-ft. cube</td></tr><tr><td>12-15</td><td>5-ft. cube</td></tr><tr><td>16-19</td><td>7-1/2-ft. cube</td></tr><tr><td>20-23</td><td>10-ft. cube</td></tr><tr><td>24+</td><td>+2-1/2-ft. per 4 points of Wisdom</td></tr></tbody></table>");