INSERT INTO Armor (Book_ID, Armor_Name, Armor_Category, Armor_Cost, Armor_AC_Bonus, Armor_Max_Dex, Armor_Check_Penalty,
    Armor_Spell_Failure, Armor_30_Speed, Armor_20_Speed, Armor_Weight, Armor_Rarity, Armor_Description)
VALUES
(4,"Feather Cloak","Light",1000.00,2,6,0,10,30,20,6,"Uncommon",
"<p>The waste is home to many birds, especially vultures. These creatures spend hours circling in the bright sunlight and baking updrafts of the desert, and their plumage helps protect them and keep them cool. Some clever waste-dwellers collect feathers and sew them onto a framework to create lightweight protection. Collecting so many feathers can take months, and considerable expertise is needed to create the garment, so feather cloaks are the purview of the wealthy and powerful. A feather cloak covers your torso and upper legs, having a broad-brimmed cap to protect the head. This type of armor does not impose the usual -4 penalty on Fortitude saves against damage dealt by hot environments and on Constitution checks to avoid heatstroke.</p>"),

(4,"Silk Swathes","Light",400.00,1,8,0,5,30,20,6,"Uncommon",
"<p>Although the desert does not support silkworms, some inhabitants of the waste have access to this exotic fabric through trade. This sheer material is perfect for clothing in hot environments, and it can be used for armor. Silk swathes are nothing more than elaborately wrapped cloth strips. Air trapped between layers allows the skin to respire, while the material itself absorbs moisture readily and dries quickly. The wrapped layers are surprisingly effective against weapon blows. However, donning this armor is time-consuming and difficult, taking as long and following the same rules as for donning full plate. Silk swathes do not impose the usual -4 penalty on Fortitude saves against damage dealt by hot environments and on Constitution checks to avoid heatstroke.</p>"),

(4,"Shield, hide","Shield",50.00,3,4,-3,30,null,null,30,"Uncommon",
"<p>This tall, oval shield is made of animal hide stretched tightly over a wood or bone framework and reinforced with strips of hide. It is relatively lightweight while still providing cover as a tower shield does. By giving up your attacks for the round, you gain total cover. The shield does not, however, provide cover against targeted spells; a spellcaster can target the shield. Since it is made of a lighter material than a tower shield, you take only a -1 penalty on attack rolls while wielding a hide shield in combat. You cannot bash with a hide shield, nor can you use your shield hand for anything else.</p>"),

(4,"Fins","Extra",50.00,0,0,0,0,null,null,2,"Uncommon",
"<p>When added to a suit of armor, these thin metal projections allow your body to radiate heat more efficiently. While wearing a suit of armor fitted with fins, you take only a -2 penalty on Fortitude saves against damage dealt by hot environments and on Constitution checks to avoid heatstroke, instead of the usual -4.</p>");