
INSERT INTO Misc_Item (Misc_Item_ID,Book_ID,Misc_Item_Name,Misc_Item_Type,Misc_Item_Cost,Misc_Item_Weight,Misc_Item_Description)
VALUES
    (135,4,"Distillation Kit","Adventuring Gear",50.00,20.00,
    "<p>Water is precious in the waste. This simple kit uses the sun and ambient heat to evaporate pure water from body or cooking waste, salt lakes, poisonous plant saps, and so on. This 'solar still' consists of a sheet of glass fastened at an angle into a frame, with a lip and a small spout (the components are packed separately and assembled when needed). The bottom and sides of the frame are covered with black oilcloth, the edges sealed with grease or tar to make it watertight. To use the still, pour the dirty water on the into the bottom of the container, then place the glass lid on top. The water evaporates and condenses on the underside of the glass surface, where it runs down and collects in the lip, dripping through the spout and producing about 1 gallon of water er day (if the container is filled to capacity).</p>"),
    
    (136,4,"Drill","Adventuring Gear",5.00,7.00,
    "<p>Whether they are used to carve sandstone, locate water, or mine salt and other precious minerals, drills are important tools in any wasteland environment. These objects can range from a primitive bow drill, suitable for perforating bone and wood, to a massive assembly of cast-iron pipes and bits, turned by wheels or beasts of burden. The drill described here is made of iron with a wooden handle, about 3 feet long. (In metal-poor areas, the bit might be of hard crystal instead of iron.) Wrapping a cord about the shaft and pulling it sharply sets the drill spinning. It can penetrate roughly 6 inches of stone per hour; the rate of drilling is faster in softer material, such as salt. A drill can be used as an improvised club or shortspear.</p>"),
    
    (137,4,"Filter Mask","Adventuring Gear",1.00,null,
    "<p>A filter mask is a fine cloth mesh, usually of silk or cotton, that covers your mouth and nose. Cords or straps fasten the cloth around the back of your head to provide a good seal. A filter mask grants a +2 bonus on saves against gas-based effects. It negates the effects of suffocation from dust and sand, as well as the effects of supernatural or magic dust (such as slumber sand) for up to 4 hours. After this time, the mesh is clogged with grit and can no longer allow air to pass through freely. A clogged filter mask requires thorough laundering before it can be reused, but most travelers simply replace it with fresh fabric.</p>");