


INSERT INTO Misc_Item VALUES
    (1,1,"Pound of Wheat","Trade Goods",0.01,1.00,null),
    (2,1,"Pound of Flour","Trade Goods",0.02,1.00,null),
    (3,1,"Live Chicken","Trade Goods",0.02,null,null),
    (4,1,"Pound of Iron","Trade Goods",0.10,1.00,null),
    (5,1,"Pound of Tobacco","Trade Goods",0.50,1.00,null),
    (6,1,"Pound of Copper","Trade Goods",0.50,1.00,null),
    (7,1,"Pound of Cinnamon","Trade Goods",1.00,1.00,null),
    (8,1,"Live Goat","Trade Goods",1.00,null,null),
    (9,1,"Pound of Ginger","Trade Goods",2.00,1.00,null),
    (10,1,"Pound of Pepper","Trade Goods",2.00,1.00,null),
    (11,1,"Live Sheep","Trade Goods",2.00,null,null),
    (12,1,"Live Pig","Trade Goods",3.00,null,null),
    (13,1,"Square Yard of Linen","Trade Goods",4.00,null,null),
    (14,1,"Pound of Salt","Trade Goods",5.00,1.00,null),
    (15,1,"Pound of Silver","Trade Goods",5.00,1.00,null),
    (16,1,"Square Yard of Silk","Trade Goods",10.00,null,null),
    (17,1,"Live Cow","Trade Goods",10.00,null,null),
    (18,1,"Pound of Saffron","Trade Goods",15.00,1.00,null),
    (19,1,"Pound of Cloves","Trade Goods",15.00,1.00,null),
    (20,1,"Live Ox","Trade Goods",15.00,null,null),
    (21,1,"Pound of Gold","Trade Goods",50.00,1.00,null),
    (22,1,"Pound of Platinum","Trade Goods",500.00,1.00,null),
    
    (23,1,"Backpack (empty)","Adventuring Gear",2.00,2.00,"<p>A backpack is a leather pack carried on the back, typically with straps to secure it.</p>"),
    (24,1,"Barrel (empty)","Adventuring Gear",2.00,30.00,null),
    (25,1,"Basket (empty)","Adventuring Gear",0.40,1.00,null),
    (26,1,"Bedroll","Adventuring Gear",0.10,5.00,"<p>You never know where you're going to sleep, and a bedroll helps you get better sleep in a hayloft or on the cold ground. A bedroll consists of bedding and a blanket thin enough to be rolled up and tied. In an emergency, it can double as a stretcher.</p>"),
    (27,1,"Bell","Adventuring Gear",1.00,null,null),
    (28,1,"Blanket, Winter","Adventuring Gear",0.50,3.00,"<p>A thick, quilted, wool blanket made to keep you warm in cold weather.</p>"),
    (29,1,"Block and Tackle","Adventuring Gear",5.00,5.00,null),
    (30,1,"Bottle, wine, glass","Adventuring Gear",2.00,null,null),
    (31,1,"Bucket (empty)","Adventuring Gear",0.50,2.00,null),
    (32,1,"Caltrops","Adventuring Gear",1.00,2.00,"<p>A caltrop is a four-pronged iron spike crafted so that one prong faces up no matter how the caltrop comes to rest. You scatter caltrops on the ground in the hope that your enemies step on them or are at least forced to slow down to avoid them. One 2-pound bag of caltrops covers an area 5 feet square.</p><p>Each time a creature moves into an area covered by caltrops (or spends a round fighting while standing in such an area), it might step on one. The caltrops make an attack roll (base attack bonus +0) against the creature. For this attack, the creature's shield, armor, and deflection bonuses do not count. (Deflection averts blows as they approach, but it does not prevent a creature from touching something dangerous.) If the creature is wearing shoes or other footwear, it gets a +2 armor bonus to AC. If the caltrops succeed on the attack, the creature has stepped on one. The caltrop deals 1 point of damage, and the creature's speed is reduced by one-half because its foot is wounded. This movement penalty lasts for 24 hours, or until the creature is successfully treated with a DC 15 Heal check, or until it receives at least 1 point of magical curing. A charging or running creature must immediately stop if it steps on a caltrop. Any creature moving at half speed or slower can pick its way through a bed of caltrops with no trouble.</p><p>The DM judges the effectiveness of caltrops against unusual opponents. A Small monstrous centipede, for example, can slither through an area containing caltrops with no chance of hurting itself, and a fire giant wearing fire giant-sized boots is immune to normal size caltrops (They just get stuck in the soles of his boots.)</p>"),
    (33,1,"Candle","Adventuring Gear",0.01,null,"<p>A candle dimly illuminates a 5-foot radius and burns for 1 hour. See page 164 of the <em>Player's Handbook</em> for more rules on illumination.</p>"),
    (34,1,"Canvas (sq. yd.)","Adventuring Gear",0.10,1.00,null),
    (35,1,"Case, map or scroll","Adventuring Gear",1.00,0.50,"<p>This capped leather or tin tube holds rolled pieces of parchment or paper</p>"),
    (36,1,"Chain (10 ft.)","Adventuring Gear",30.00,2.00,"<p>Chain has hardness 10 and 5 hit points. It can be burst with a DC 26 Strength check.</p>"),
    (37,1,"Chalk, 1 piece","Adventuring Gear",0.01,null,null),
    (38,1,"Chest (empty)","Adventuring Gear",2.00,25.00,null),
    (39,1,"Crowbar","Adventuring Gear",2.00,5.00,"<p>This iron bar is made for levering closed items open. A crowbar is the perfect tool for prying open doors or chests, shattering chains, and the like, and it grants a +2 circumstance bonus on Strength checks made for such purposes. If used in combat, treat a crowbar as a one-handed improvised weapon (see page 113 of the <em>Player's Handbook</em>) that deals bludgeoning damage equal to that of a club of its size.</p>"),
    (40,1,"Firewood (per day)","Adventuring Gear",0.01,20.00,null),
    (41,1,"Fishhook","Adventuring Gear",0.10,null,null),
    (42,1,"Fishing Net, 25 sq. ft.", "Adventuring Gear",4.00,5.00,null),
    (43,1,"Flask (empty)","Adventuring Gear",0.03,1.50,"<p>This ceramic, glass, or metal container is fitted with a tight stopper and holds 1 pint of liquid.</p>"),
    (44,1,"Flint and Steel","Adventuring Gear",1.00,null,"<p>Striking steel and flint together creates sparks. By knocking sparks into tinder, you can create a small flame. Lighting a torch with flint and steel is a full-round action, and lighting any other fire with them takes at least that long.</p>"),
    (45,1,"Grappling Hook","Adventuring Gear",1.00,4.00,"<p>When tied to the end of a rope, a grappling hook can secure the rope to a battlement, window ledge, tree limb, or other protrusion. Throwing a grappling hook successfully requires a Use Rope check (DC 10,+2 per 10 feet of distance thrown).</p>");