
INSERT INTO Spell
(Spell_ID, Book_ID, Spell_Name, Spell_School, Spell_Subschool,
Spell_Descriptor, Spell_Components, Spell_Casting_Time, Spell_Range,
Spell_Effect, Spell_Target, Spell_Duration, Spell_Saving_Throw,
Spell_Resistance, Spell_Short_Description, Spell_Description,
Spell_Material_Component, Spell_Focus, Spell_XP_Cost)
VALUES

    (607,3,"Aboleth Curse","Necromancy",null,null,"V, S, M",
    "1 standard action","Touch",null,"Living creature touched",
    "Permanent","Fortitude negates","Yes",
    "Subject's skin undergoes a horrible transformation.",
    "<p>You bestow a dreadful affliction on the creature that you touch, similar to the effect of an aboleth's foul contact. The skin of the target creature transforms into a transparent, glistening membrane. A creature so transformed must keep this membrane moistened with cool, fresh water or take 1d12 points of damage every 10 minutes. In addition, its natural armor bonus (if any) decreases by 1, but it can never drop below 0. This tranformation does not affect natural armor bonuses provided by magic items.</p><p>This curse cannot be dispelled, but it can be removed with a <em>remove curse</em> spell if cast within 24 hours. Afterward, only a <em>heal</em>, <em>mass heal</em>, <em>limited wish</em>, <em>miracle</em>, or <em>wish</em> spell can remove the affliction.</p>",
    null, null, null),
    
    (608,3,"Air Breathing","Transmutation",null,"Air","S, M/DF",
    "1 standard action","Touch",null,"Living creatures touched",
    "2 hours/level","Will negates (harmless)","Yes (harmless)",
    "Subject breathes air as easily as water.",
    "<p>The transmuted creature can breathe air freely. Divide the duration evenly among all the creatures you touch.</p><p>This spell does not make creatures unable to breathe water.</p><p><em>Air breathing</em> counters and dispels </em>water breathing</em>.</p>",
    "Arcane Material Component: A tiny vial of water",null,null),
    
    (609,3,"Airy Water","Transmutation",null,"Air, Water", "S, M",
    "1 standard action","0 ft.","20-ft.-radius emanation centered on you",
    null,"10 min./level (D)","None","No",
    "Turn normal water into a breathable substance; negate underwater movement and melee attack penalties.",
    "<p>This spell turns normal water (or watery solutions) into a frothy substance that is as breathable as air. Both air-breathing and water-breathing creatures witin the area can breathe normally.</p><p>Moving through <em>airy water</em> is easier than moving through normal water. Swimmers make a DC 10 Swim check once per round; they swim at their normal speed on a success, or half their normal speed on a failure. Creatures with a swim speed can simply use their swim speed without penalty. Creatures can instead use their land speed to move along the bottom at their normal speed. Creatures walking on the bottom do not pay any movement penalty for walking on sand, stone, or pebble seafloor and only pay 2 squares of movement per square of muck or mud entered (see Marine Dungeon Terrain on page 21 of Stormwrack).</p><p>Finally, <em>airy water</em> negates underwater combat penalties for all melee attacks, although ranged attacks still take the normal underwater penalty.</p><p>The spell does not filter or purify solid particles, so casting <em>airy water</em> on very turbid liquids, for example, would produce an area filled with dust or smoke (and impose similar penalties).</p>",
    "Material Component: A small handful of alkaline salts.",
    null,null),
    
    (610,3,"Blackwater Taint","Necromancy",null,"Evil, Water", "V, S, M",
    "1 standard action","Medium","20-ft. radius",null,"1 round/level (D)",
    "Fortitude Partial","Yes",
    "Desecrate water, deal 1d6/2 levels negative energy damage, bestow a negative level.",
    "<p>In the dark, sunless abysses of the deep ocean, shadows gather, the cold beckons, and the corpses of many things in the oceans lie slowly rotting. These black waters are often poisoned with the energies of undeath. When this spell is cast, you call up the cold blackness of those stygian depths, infusing the waters in the spell's area with negative energy. Those in or entering the area must make a Fortitude save to resist its terrible power.</p><p>Those who fail the save are chilled to the bone, taking 1d6 points of damage per two levels (to a maximum of 10d6) and gain a negative level. Those who make the save take half damage and avoid the negative level. All undead in the area are healing qd6 points of damage per two caster levels (maximum of 10d6). Furthermore, the spell's area is treated as though there were a <em>desecrate</em> spell active within it.</p><p>This area of blackwater remains in place for the spell's duration, affecting creatures who enter the area in subsequent rounds. A creature can only be affected once by the spell, regardless of success or failure on the saving throw, so creatures who leave and reenter the area take no additional effect (although the <em>desecrate</em> effect remains throughout the spell's duration).</p>",
    "Material Component: Bone or scale of a fish that dwells in the deep, sunless parts of the ocean.",
    null,null),
    
    (611,3,"Blackwater Tentacle","Conjuration","Creation","Evil, Water","V, S, M",
    "1 standard action","Close","One tentacle",null,"1 round/level (D)",
    "Fortitude partial","No",
    "Create blackwater tentacle that attacks your foe.",
    "<p>You create a tentacle-shaped mass of blackwater, drawn from the deepest ocean trenches, to attack an enemy as you direct it. The tentacle appears at a particular point within range and can't move from that location. It attacks the opponent you designate once each round, starting with the round the spell is cast. It has a reach of 20 feet (though it can't make attacks of opportunity).</p><p>Its attack bonus is equal to your caster level plus the ability modifier you would normally use to set the save DC (Wisdom for cleric or druid, Intelligence for wizard, Charisma for sorceror). The tentacle deals 2d8 + caster level (max. +20) points of damage with a successful hit. Any Large or smaller creature hit by a blackwater tentacle must succeed on a Fortitude save or gain a negative level. Multiple hits by the same tentacle are cumulative, but the negative levels last only for the duration of the spell.</p><p>The tentacle never provides nor benefits from a flanking bonus. Once a tentacle has been directed to attack a foe, it continues to do so until the spell is redirected to a new target (a move action).</p><p>The tentacle has 5 hit points per caster level and an AC of 10 + your caster level. It automatically fails all saves. If reduced to 0 hp, the tentacle is destroyed.</p>",
    "Material Component: Powdered squid beak and a single dried sucker from a kraken's tentacle.",
    null,null),
    
    (612,3,"Control Currents","Transmutation",null,"Water","V, S",
    "1 standard action","20 ft./level","20-ft./level radius emanation centered on you",null,
    "10 min./level","None","No",
    "Changes current direction and speed.",
    "<p>You alter the flow of water in the area surrounding you. You can change the direction of an existing current, boost its strength, or cause still water to flow at a desired rate. The new current speed and direction persists until the spell ends or you decide to alter the effect, which requires concentration. You can choose to create an area of calm water up to 80 feet in diameter at the center of the affected area if you so desire, and you can create a limited effect in a smaller circular area within the spell's range.</p><p><em>Current Direction: </em>You can choose one of two basic current patterns to function over the spell's area.</p><ul><li>You can direct the current to flow in one direction across the entire area from one side to the other.</li><li>You can create a rotation, causing the water to swirl around the center in a clockwise or counterclockwise direction.</li></ul><p><em>Current Strength: </em>For every three caster levels, you can increase or decrease a current's speed by 10 feet. For example, a 9th level druid could increase the speed of a vigorous current (20 feet per round) to a dangerous current (50 feet per round) or reduce it to calm, placid water. See Currents and Streams, page 10 of Stormwrack, for more information about current strength and Swim checks.</p>",
    null,null,null),
    
    (613,3,"Dark Tide","Necromancy",null,"Evil, Water","V, S, DF",
    "1 full round","Long","One-half mile radius spread",null,"1 hour/level (D)",
    "Fortitude half","Yes",
    "Infuse water over a large area with negative energy and 1d6 damage/hour.",
    "<p>You infuse the target area with the enervating presence of the blackwater depths, creating a tide of blackwater that spreads out from the designated point of origin at a rate of 100 feet per round until it fills the entire area. The water is black and terribly chilling, and its touch causes a sense of fear in those affected by it.</p><p>Those within the area must make a Fortitude save when they first enter the blackwater (or when it first surrounds them). Failure indicates that they take 1 point of Strength damage. Additionally, every creature in the area takes 1d6 points of negative energy damage for every hour they remain in the dark, murky waters (no save). Spells that protect against negative energy damage will prevent the Strength damage.</p><p>Creatures who take damage from the <em>dark tide</em> are considered shaken as long as they remain in the area.</p><p>This spell is a favored first move of the sahuagin and other blackwater-dwelling creatures before they attack the settlements of their enemies.</p>",
    null,null,null),
    
    (614,3,"Depthsurge","Evocation",null,"Water","V, S, M",
    "1 standard action","Long","20 ft. radius",null,"Instantaneous",
    "Fortitude partial","Yes",
    "Water slam deals 2d6 + caster level damage to all within 20-ft. radius, pushes targets back, sinks ships.",
    "<p>The water within the area suddenly explodes outward in a massive surge, as if driven by a powerful explosion. Each creature or object in the area is subject to damage equal to 2d6 + caster level. Any creature struck by this attack must then succeed on a Fortitude save or be driven 10 feet away from the center of the blast.</p><p>If a ship is in the area, the captain must immediately make a sinking check (DC equal to the spell save DC). See Sinking, page 32 of Stormwrack.</p><p>At least half of the spell's area must contain water at least 10 feet deep, or else the spell fails. You must center the effect at or below the water's surface.</p>",
    "Material Component: A sphere of volcanic rock",
    null,null),
    
    (615,3,"Detect Ship","Divination",null,null,"V, S, F",
    "1 standard action","Special",null,"You","24 hours (D)",
    "None","No",
    "Detect and identify ships.",
    "<p>You gain the ability to discern the presence of ships around you. You perceive ships located within a distance of 1 mile per caster level, regardless of current visibility (or even whether or not they are beyond the horizon). You need not be seeking them to become aware that they are there - this spell will alert you to the presence of a ship if you are below decks or asleep. Exactly what can be ascertained depends on whether the ships in question are within sight or not yet visible.</p><p><em>Not Visible: </em>You sense only the presence of ships other than your own in the area. A DC 15 Profession (sailor) check allows you to determine the number, direction, and range to each new ship you sense. If you sense a ship's direction and range, you continue to be aware of this information until the other ship is no longer in range of the spell.</p><p><em>Within Sight: </em>If a ship is actually within sight, you can gain additional information by studying the vessel for 1 round. You need not be able to see the vessel clearly - a spot on the horizon is sufficient. A Profession (sailor) check gives you information about the ship or ships:</p><table><thead><tr><th><strong>Check Result</strong></th><th><strong>Information</strong></th></tr></thead><tbody><tr><td>10</td><td>Type of ship</td></tr><tr><td>12</td><td>Course, speed, and time to intercept (if possible)</td></tr><tr><td>15</td><td>What kind of weaponry the ship is carrying</td></tr><tr><td>18</td><td>Ship's name</td></tr><tr><td>20</td><td>Any signs of allegiance (pirate flags, symbols of nation of origin, etc.)</td></tr><tr><td>25</td><td>Port of call of the sighted ship</td></tr></tbody></table><p>This spell cannot penetrate illusions.</p>",
    null,"Focus: A small disk of ground glass, hung on a golden chain and worn about the neck while the spell is in effect. This focus is worth 50 gp.",
    null),
    
    (616,3,"Disguise Ship","Illusion","Glamer",null,"V, S, M",
    "1 standard action","Touch",null,"One ship","1 hour/level (D)",
    "Will disbelief (if interacted with)","No",
    "Disguises a ship.",
    "<p>You cloak a ship in illusion, making it appear as a ship of another type of your choice. You can choose what it appears as down to small details such as what weaoonry it bears and what flag it is flying. You can make the ship to be any other water-going vessel, though it cannot seem to be more than 50% smaller or larger.</p><p>Creatures within the area are not hidden or changed in appearance, nor are their possessions.</p>",
    "Material Component: A tiny replica of a ship",
    null,null),
    
    (617,3,"Doom of the Seas","Conjuration","Summoning","Evil","V, S, DF, XP",
    "1 full round","Touch","One summoned creature",null,"1 round/level (D)",
    "None","No",
    "Summons a fiendish kraken under your command.",
    "<p>It is said that in the deepest recesses of blackwater caverns dwell krakens of immense power, horrific creatures touched by malevolent extraplanar powers. Though this might certainly be true, it is likely that most experiences with such creatures comes as a result of this spell.</p><p>With this spell, you summon a fiendish kraken from the depths. The doom of the seas obeys you for the duration of the spell.</p>",
    null,null,"XP Cost: 500 XP."),
    
    (618,3,"Favorable Wind","Evocation",null,"Air","V, S",
    "1 standard action","60 ft.","Cone-shaped emanation",null,"10 min./level (D)",
    "Fortitude negates","No",
    "Produces a strong wind that lasts 10 min./level",
    "<p>This spell produces a stream of wind that can fill a ship's sails, disperse vapors and gases, and keep flying creatures at bay. The wind force is strong, with a speed of about 30 mph. It begins where you stand and blows directly away from you; you can easily propel a sailing vessel by standing astern of the mast and directing the wind forward to fill the sails.</p><p>Tiny or smaller creatures in the path of the wind are knocked prone, or if flying are blown back 1d6x10 feet.</p><p>Small creatures are checked and cannot make headway against the wind. Small airborne creatures are instead blown back 1d6x5 feet.</p><p>Medium and larger creatures can move normally within the effect.</p><p>A <em>favorable wind</em> can't push a creature beyond the limit of its range.</p><p>Any creature, regardless of size, takes a -2 penalty on ranged attacks and on Listen checks in the area of a <em>favorable wind</em>.</p><p>The wind automatically extinguishes candles, torches, and similar unprotected flames.</p><p>In addition to the above-noted effects, <em>favorable wind</em> can do anything that a strong natural wind could do. It can fan a large fire, disperse gases and vapors to the limit of its range in 1 round, and make sailing difficult for small craft nearby.</p>",
    null,null,null),
    
    (619,3,"Fins to Feet","Transmutation",null,null,"V, S",
    "1 standard action","Touch",null,"Willing creature touched","1 hour/level",
    "Fortitude negates (harmless)","Yes (harmless)",
    "Transforms tails, tentacles, or finned extremities into humanoid legs and feet.",
    "<p>This spell transforms tails, tentacles, or finned extremities into humanoid legs and feet. Creatures so affected lose any natural swim speed they possess but gain a land speed instead. Transmuted Medium creatures have a base land speed of 30 feet, Small and smaller creatures have a base land speed of 20 feet, and Large or larger creatures have a base land speed of 40 feet.</p><p>The creature loses any natural attacks based on its tail or tentacles.</p>",
    null,null,null),
    
    (620,3,"Flowsight","Divination","Scrying",null,"V, S, M/DF",
    "1 minute","Touch","60-ft. radius",null,"1 round/level (D)",
    "Will negates; see text","Yes",
    "You can scry creatures in contact with a body of water.",
    "<p>By touching a nearby sorce of water - a standing pool, a stream, or even a portion of a larger body of water - you can perceive creatures and objects in contact with the water.</p><p>You can concentrate to focus <em>flowsight</em> on a given creature. You retain your full visual acuity, including any magical effects, as well as any auditory enhancements you might have. This action makes the subject potentially aware of the magical scrying; on a Will save, it prevents you from learning more about it, and you cannot try again on that subject for 24 hours. However, you can turn your consciousness to another subject in contacted with the water and make a new scrying attempt each round.</p>",
    "Arcane material component: A piece of limestone",
    null,null),
    
    (621,3,"Jaws of the Moray","Transmutation",null,null,"V, S",
    "1 standard action","Touch",null,"Creature touched","1 min./level",
    "Will negates (harmless)","Yes (harmless)",
    "Subject gains a bite attack.",
    "<p>This spell grants the subject a bite attack, which deals damage as indicated below. As a primary attack, it adds the creature's Strength modifier to damage. It can also be used as a secondary natural attack in conjunction with a manufactured weapon. Such secondary attacks do not interfere with the primary attack as attacking with an off-hand weapon would do, but the subject takes the usual -5 penalty (or -2 with the Multiattack feat) for the bite attack when used as a secondary natural attack.</p><p>If the subject hits with its bite attack, it attaches itself to the foe and deals automatic bite damage each round it remains attached. It does not need to make a grapple check, and it does not provoke attacks of opportunity. An attached attacker loses its Dexterity bonus to Armor Class. It cannot use other weapons while attached, but each attack upon from the grappled foe requires a successful grapple check. Others can attack an attached creature with a weapon or grapple. To remove the attached creature through grappling, the opponent must achieve a pin against it.</p><p>A creature with a natural bite attack can use its own bite damage, if greater, but still gains the ability to attach itself.</p><table><thead><tr><th><strong>Size</strong></th><th><strong>Damage</strong></th></tr></thead><tbody><tr><td>Fine</td><td>1d2</td></tr><tr><td>Diminutive</td><td>1d3</td></tr><tr><td>Tiny</td><td>1d4</td></tr><tr><td>Small</td><td>1d6</td></tr><tr><td>Medium</td><td>1d8</td></tr><tr><td>Large</td><td>2d6</td></tr><tr><td>Huge</td><td>2d8</td></tr><tr><td>Gargantuan</td><td>4d6</td></tr><tr><td>Colossal</td><td>4d8</td></tr></tbody></table>",
    null,null,null),
    
    (622,3,"Jig of the Waves","Enchantment","Compulsion","Mind-Affecting","V, S",
    "1 standard action","Close","One or more creatures in a 10-ft.-radius burst",null,"Concentration + 1d4 rounds",
    "Will negates","Yes",
    "Force creature to dance a jig which causes penalties and forces random movement.",
    "<p>You cause one or more creatures to begin dancing a merry jig. This spell affects a number of HD of creatures equal to the caster level. Creatures with the fewest HD are affected first. Among creatures with equal HD, those who are closest to the spell's point of origin are affected first. Hit Dice that are not sufficient to affect a creature are wasted.</p><p>Those who are dancing receive a -2 penalty on attack rolls, saving throws, skill checks, ability checks, and Armor Class for the time that they dance. Though they can take actions normally (using the penalties given above), their movement is not their own.</p><p>Each round, a creature affected by this spell must take a move action to move half her speed in a random direction. If this movement would place the target in danger (such as dancing into a fire or off the deck), the dance causes the target to stop just short of the threat. Targets can still take their actions, either before or after their movement as they choose.</p>",
    null,null,null),
    
    (623,3,"Kuo-Toa Skin","Transmutation",null,null,"V, S, M/DF",
    "1 standard action","Touch",null,"Creature touched","1 hour/level",
    "Will negates (harmless)","Yes (harmless)",
    "Subject gains +8 on Escape Artist checks and cannot be ensared by webs.",
    "<p>The subject's skin, as well as clothing, armor, and other personal effects (including worn magic items), take on an oily sheen like the slippery skin of kuo-toas. For the duration of the spell, the subject gains a +8 bonus on Escape Artist checks and cannot be snared by webs (magical or otherwise).",
    "Arcane Material Component: A kuo-toa scale",
    null,null),
    
    (624,3,"Maelstrom","Conjuration","Creation","Water","V, S, DF",
    "1 full round","Long","Whirpool 120 ft. wide and 60 ft. deep",null,"1 round/level",
    "Reflex negates","No",
    "Conjures a deadly whirpool to suck in and batter foes.",
    "<p>This spell causes a deadly vortex to form in water. A body of water at least 120 feet wide and 60 feet deep must be present, or the spell is wasted.</p><p>Waterborne creatures or objects within 50 feet of the vortex (below and on all sides) must make Reflex saves or be sucked in. These creatures take 3d8 points of damage upon being sucked in. Trained swimmers can attempt Swim checks instead if their skill modifier is higher than their Reflex save bonus. Waterborne vessels avoid being sucked in if their operators make Profession (sailor) checks against the same DC as the spell's saving throw.</p><p>Once inside, creatures and objects take 3d8 points of battering damage each round. They remain trapped for 2d4 rounds. Subjects of Large or smaller size are ejected from the bottom of the vortex. Huge, Gargantuan, or Colossal subjects are ejected from the top.</p>",
    null,null,null),
    
    (625,3,"Megalodon Empowerment","Transmutation",null,null,"V, S, M",
    "1 standard action","Personal",null,"You","1 hour/level or 1 round/level (D)",
    null,null,
    "Gain scent, water breathing, swim speed for 1 hour/level.",
    "<p>The mighty megalodon is a terror to most things that swim. However, it is also undeniably perfect in its form, made to be the ultimate hunting machine. When this spell is cast, you take on some of the essence of this greatest of sharks. You become a predator without peer, capable of finding and destroying your prey.</p><p>When the spell is initially cast, you take what is called the Form of the Hunter: your features undergo a subtle change, becoming more angular. Your skin darkens to a blue-black hue and becomes slightly rough to the touch. Your sense of smell sharpens, granting you the scent special ability and a +10 racial bonus to Survival checks for the purpose of tracking by scent. Additionally, your swim speed increases by 10 feet; if you do not already possess a swim speed then you gain a swim speed equal to your normal land movement. You also gain the ability to breathe water. You retain this form for up to 1 hour per caster level (as noted above).</p><p>At any time during the spell's duration, you can shift into the terrible Form of the Killer as a standard action. Doing so dramatically reduces the remaining time of the spell, however, reducing it to 1 round per caster level, regardless of how much time was originally remaining.</p><p>In the Form of the Killer, you swell in size, increasing by one size category (see page 291 of the <em>Monster Manual</em> for guidelines on changes to abilities and traits for such a change). You retain the scent and swim speed benefits of the Form of the Hunter, and the rough hide of the megalodon fully manifests - those who strike you with unarmed or natural attacks must make a Reflex save or take 1d4 points of damage.</p><p>You also gain bite and claw natural attacks and are considered to have the Multiattack feat for the purpose of using them. These natural attacks deal damage according to your new size (see page 296 of the <em>Monster Manual</em> for details): for a Medium caster this gives a bite attack for 1d8 points of damage and two claw attacks for 1d6 points of damage).</p><p>Finally, your base attack bonus equals your character level, you gain a +4 natural armor bonus (in addition to that gained from the size increase), and you gain a +3 competence bonus on Fortitude and Reflex saves.</p><p>You lose the ability to cast spells (but not to use spell-like abilities). If you possess the wild shape ability, you can assume the shapes of animals one size category larger than normal.</p><p>Assuming the Form of the Killer lasts for the duration of the spell - once it has been done, you cannot return to the Form of the Hunter without recasting.</p>",
    "Material Component: A potion of water breathing and three teeth from a shark of at least Large size.",
    null,null),
    
    (626,3,"Capable Caravel","Conjuration","Creation",null,"V, S, F",
    "10 minutes","Close","Ship plus extradimensional space, up to three 10-ft. cubes/level (S)",null,"1 day/2 levels (D)",
    "None","No",
    "Creates magical ship with extradimensional staterooms.",
    "<p>You conjure into existence a fine, seaworthy ship to carry you and your companions safely and comfortably.</p><p>A caravel is a fairly small, double-decked sailing ship (see page 98 of <em>Stormwrack</em> for more information). It holds a generous amount of cargo and offers cramped quarters for crew and passengers. The ship produced by this spell has even more room for cargo and passengers. The ship produced by this spell has even more room for cargo and passengers within an extradimensional space.</p><p>The entry point to this space is a hatch on the aft upper deck. Lifting the hatch reveals a set of wooden stairs, which descend about 6 feet to a horizontal shimmering in the air about 4 feet wide. Only those you designate can enter this space, and the extradimensional portal is shut and made invisible behind you when you enter. Those without authorization to enter instead continue descending the steps to an ordinary cargo hold. You can open the portal again from your own side at will.</p><p>Those who pass beyond the portal's entrance find themselves in a magnificent foyer with many state-rooms whose doors open from this space. The atmosphere is clean, fresh, and warm.</p><p>You can create any deck plan you desire within the limit of the spell's effect. The cabins are furnished, and the galley contains sufficient foodstuffs and preparation equipment to serve three full meals per day per person per caster level. A staff of near-transparent pursers (up to two per caster level), liveried and obedient, wait upon all who enter. They function as <em>unseen servant</em> spells except that they are visible and can go anywhere within the extradimensional space.</p><p>Since the place can be entered only through its special portal, outside conditions do not affect the passenger space, nor do conditions inside it pass to the plane beyond. Bad weather or other marine hazards can still threaten the vessel, but even if it sinks, the passenger space remains safe and isolated (though exiting it might prove difficult).</p><p>The ship is crewed by a minimum complement of spectral deckhands, which perform the basic tasks of maintenance. These, like the cabin servants, behave as <em>unseen servants</em> but can travel anywhere on board ship and can enter the extradimensional space if you so direct. The spectral deckhands respond to the direction of the helmsman, reducing the number of crew necessary to control the caravel to 1. If you do not provide a real helmsman, the ship will steer itself on the last course a living helmsman provided but will not be able to avoid collisions or hazards or adjust to changing conditions.</p>",
    null,"Focus: A miniature ship carved from mahogany, rigged with silk sails and gold thread, with a total value of 500 gp.",
    null),
    
    (627,3,"Mudslide","Conjuration","Creation","Earth, Water","V, S, M/DF",
    "1 standard action","Medium","40-ft.radius spread",null,"Instantaneous",
    "Reflex half; see text","No",
    "Landslide buries, mires creatures within a 40-ft. radius.",
    "<p>You create a landslide of mud and water, which crushes, buries, and mires those caught in its path. The mud covers the area of the spell to a depth of about 10 feet (although it might fill low-lying areas or fail to cover high points in the area, at the DM's discretion).</p><p>Creatures within the spell's effect must make a Reflex save. Those who fail take 8d6 points of damage and are buried (see Avalanches on page 90 of the <em>Dungeon Master's Guide</em>). Those who succeed take 3d6 points of damage and are not buried. Creatures of the fire subtype who are actually aflame (such as salamanders, azers, and fire elementals) instead take 8d8 or 3d8 points of damage, respectively. A creature who escapes burial ends up on top of the mudslide, mired in deep mud.</p><p>After the initial slide, the mudslide persists indefinitely, producing an area of deep bog (average depth 10 feet) until the water in it evaporates. It requires 4 squares of movement to enter 1 square of deep bog, and running or charging are impossible in the area. Underwater, the mudslide remains indefinitely, producing an area of deep muck. It costs 2 squares of movement to enter a square containing deep muck, the DC of Balance and Tumble checks increases by 5, and the DC of Move Silently checks increases by 2. Aboveground, the mud normally dries out in 2 to 3 days. A <em>transmute mud to rock</em> spell hardens the slide into stone, trapping any creatures still within.</p>",
    null,null,null),
    
    (628,3,"Planar Navigation","Conjuration","Teleportation",null,"V, S, F/DF",
    "1 minute","Touch",null,"One ship","Instantaneous",
    "Will negates","Yes",
    "Send a whole ship to another plane.",
    "<p>You move yourself and the contents of an entire ship to another plane of existence. When you begin casting the spell, a fog descends about the vessel, and clears within a minute. The ship always appears on a body of water large enough for the ship to sit in safely, unless the destination plane has no body of water large enough to hold the ship, in which case the ship simply materializes the right side up, lying on the ground. If the destination plane is one that possesses an ocean, the ship automatically appears there.</p><p>Note that this spell does not grant the ship or its inhabitants any ability to survive on the destination plane - the ship simply appears in the plane upon a body of water (or, in the case of planes that are made up of nothing but water, <em>in</em> the water.</p><p>Any characters of creatures aboard unwilling to move to the new plane are entitled to a Will saving throw to resist the effect, but might find themselves floating in the water when the ship vanishes from around them.</p>",
    null, "Arcane Focus: A sextant (see page 108 of <em>Stormwrack</em>).",
    null),
    
    (629,3,"Pressure Sphere","Evocation",null,"Water","V, S",
    "1 standard action","Medium","20-ft.-radius spread",null,"Instantaneous",
    "Fortitude half","Yes",
    "Water pressure deals 4d6 damage to submerged targets.",
    "<p>This spell suddenly causes the water around a target to take on the terrible, bone-crushing pressure of the deepest ocean trenches. This pressure deals 4d6 points of damage (Fortitude save for half).</p><p>The area of the spell can be constrained by the available water; it has no effect on creatures or objects that are within the radius but not in the water, or on squares of water that are not at least 5 feet deep. The spell must be centered at or below the surface of the water.</p>",
    null,null,null),
    
    (630,3,"Quickswim","Transmutation",null,null,"V, S, M/DF",
    "1 standard action","Personal",null,"You","1 hour/level (D)",
    null,null,
    "Your swim speed increases by 10 ft.",
    "<p>This spell increases your base swim speed by 10 feet; this adjustment counts as an enhancement bonus. It has no effect on other modes of movement, such as land speed, burrow, climb, or fly. If you do not have a swim speed, you gain no benefit from this spell.</p>",
    "Arcane Material Component: A scale from any fish.",
    null,null),
    
    (631,3,"Rapture of the Deep","Enchantment","Charm","Mind-Affecting","V, F",
    "1 standard action","Medium",null,"One living creature","Permanent (D)",
    "Will negates","Yes",
    "Target becomes comatose.",
    "<p>You fill the target creature's thoughts and ears with the sublime music of the deep waters. The creature is completely immersed in this sensation and does nothing but experience it fully. It enters a comatose state and cannot be awakened by any means short of dispelling the effect. This is not a sleep effect, so elves and dragons are not immune to it. <em>Dispel magic</em> and <em>break enchantment</em> cannot remove this effect, but a <em>heal</em>, <em>limited wish</em>, <em>miracle</em>, or <em>wish</em> spell restores the creature to consciousness.</p><p>An air-breathing creature in the water affected by this spell begins to sink and will drown if not rescued. A flying creature immediately falls and might take falling damage. Damage does not awaken the charmed creatures.</p>",
    null,"Focus: A conch shell",
    null),
    
    (632,3,"Red Tide","Evocation",null,"Water","V, S, DF",
    "1 standard action","Medium","Burst in the shape of a circular disk, 10 ft. wide/level, 5 ft. high",null,"Instantaneous",
    "Fortitude partial; see text","Yes",
    "Creates a surge of tainted water that sickens, weakens, and nauseates.",
    "<p>This visually impressive spell causes a surging, frothing wave of thick, red seawater that washes over everything in the area. All creatures in the area of a <em>red tide</em> are immediately knocked prone and must make a Fortitude saving throw. Flying or swimming creatures in the area aren't knocked prone, but they take a -4 penalty on the Fortitude save.</p><p>A living creature who makes its Fortitude save against a <em>red tide</em> is sickened for 1 minute and takes a -2 penalty on attack rolls, weapon damage rolls, saving throws, skill checks, and ability checks for that time. A creature who fails this saving throw feels the full effect of the <em>red tide</em> Such creatures are immediately nauseated for 1 minute (unable to attack, cast spells, or concentrate), and they take 3d6 points of Strength damage. After 1 minute, the nausea ends, but the creature must make a second Fortitude saving throw or take an extra 3d6 points of Strength damage. Creatures immune to poison are immune to these effects of a <em>red tide</em>.</p><p>The tainted water evoked by this spell vanishes after a few seconds of turbulence, and any objects or creatures in the area do not emerge wet. All open flames in the area are nevertheless extinguishes if they fail a Reflex save, and all creatures with the fire subtype take 1d6 points of damage per caster level (maximum 20d6; Fort save half).</p>",
    null,null,null),
    
    (633,3,"Roar of the Waves","Illusion","Pattern","Fear, Mind-Affecting, Sonic","V, S, M",
    "1 standard action","Close",null,"One target/2 levels, no two of which can be more than 30 ft. apart","1 round/level (D)",
    "Will partial; see text","Yes",
    "Make one target/2 levels deafened and shaken.",
    "<p>The ocean's voice is a terrible and majestic thing. Bards understand the power of the ocean's song and have harnessed that in this spell.</p><p>The targets of this spell are suddenly bombarded by the sound of the roaring ocean. The target is deafened for the duration of the spell. Additionally, each target must make a Will save or be shaken.</p><p>This sound can be heard by anyone within 30 feet of the targets, but only those actually targeted are affected.</p>",
    "Material Component: Pieces of shell that have been battered by the surf.",
    null,null),
    
    (634,3,"Scales of the Sealord","Transmutation",null,null,"V, S, M",
    "1 standard action","Personal",null,"You","1 hour/level (D)",
    null,null,
    "Add 10 ft. to swim speed or gain swim speed of 15 ft; add natural armor bonus +1/3 levels.",
    "<p>You transform yourself into a form better suited to the watery environment, growing shimmering scales and gaining webbed hands and feet. For the duration of the spell, your swim speed increases by 10 feet.</p><p>If you had no swim speed, you gain a swim speed of 15 feet, gaining a +8 racial bonus on any Swim check to perform some special action or avoid a hazard. You can always choose to take 10 on a Swim check, even if distracted or endangered. You can use the run action while swimming, provided you swim in a straight line.</p><p>Finally, you gain a natural armor bonus +1/three caster levels, maximum of +5. However, because of your strange appearance, you gain a penalty to Charisma-based checks equal to the natural armor bonus when dealing with nonaquatic creatures.</p>",
    "Material Component: Handful of thick scales.",
    null,null),
    
    (635,3,"Sink","Transmutation",null,"Water","V, S",
    "1 standard action","Medium",null,"One living creature","1 min./level (D)",
    "Fortitude negates","Yes",
    "Subject loses buoyancy.",
    "<p>The target creature loses its natural buoyancy, sinking like a stone in water or liquids of similar density (but not mud or lava). Each round, the affected creature must make a DC 25 Swim check simply to keep its head above water, or a DC 30 Swim check to move 5 feet in any direction. Failing a check by 5 or more causes the target to go underwater, and it must hold its breath or begin to drown (see Drowning on page 304 of the <em>Dungeon Master's Guide</em>). Failing a check by 10 or more causes the target to sink 5 feet. A DC 25 Swim check is needed to surface by 5 feet.</p><p>A creature under the effect of <em>sink</em> is adequately ballasted to walk on the bottom, if it so chooses.</p><p>A creature with a swim speed takes a -10 ft. penalty to its swim speed (minimum 5 ft.) and sinks 5 feet every round at the end of its turn unless it succeeds on a DC 25 Swim check.</p><p><em>Sink</em> counters and dispels <em>wave blessing</em>.</p>",
    null,null,null),
    
    (636,3,"Siren's Call","Enchantment","Compulsion","Mind-Affecting","V, S",
    "1 action","Close",null,"One creature/2 levels, no two of which can be more then 30 ft. apart","1 round/level (D)",
    "Will negates","Yes",
    "Compel one creature/2 levels to submerse itself.",
    "<p>The targets of this spell hear a sudden, distant song that instills in them a longing for the sea. Those who have heard it compare it to the song of a siren.</p><p>A target who fails a saving throw against this spell moves immediately toward the nearest stretch of ocean that it can find and attempts to completely submerse itself in the water. This flight will be by the safest means possible, withdrawing from combat, fighting defensively, and not passing through threatened areas.</p><p>The target will only fight if someone actively attempts to prevent it from following through with its search for the ocean; if this fight is with an ally, the target is granted a second saving throw to throw off the effects of the spell.</p><p>In some environments, this means that those affected simply flee in the direction of the nearest coast. Along a shoreline, targets often plunge into the surf. Aboard ship, they leap overboard. If the subject has no idea where to find a substantial body of water, it simply chooses a random direction and continues until the spell expires.</p><p>Once the spell's subjects are in the water, they begin swimming toward the deepest part of it they can reach, immersing themselves completely and redusing to come up for air, though they hold their breath as long as they are able.</p>",
    null,null,null),
    
    (637,3,"Steed of the Seas","Transmutation",null,null,"V, S, DF",
    "1 standard action","Touch",null,"Your mount","2 hours/level (D)",
    "None","Yes",
    "Make your special mount amphibious.",
    "Paladins are understandably loathe to enter into the water depths without their loyal steeds to assist them. With this spell, you imbue your mount with the ability to enter the water without harm by granting it the aquatic subtype. Additionally, the mount gains a swim speed equal to half its normal speed.</p><p>A mount under the effects of this spell is able to breathe water; in fact, it is amphibious and thus subject to no ill effect in or out of the water.</p>",
    null,null,null),
    
    (638,3,"Stormrunner's Ward","Abjuration",null,null,"V, S, M",
    "1 full round","Touch",null,"One ship","1 hour/level (D)",
    "None","No",
    "Add +4 (+1/4 levels) to ship's checks to weather storms.",
    "<p>You ward a single ship against foundering and storm damage, making it easier to sail in dangerous wather. You add a +4 bonus on any checks made to sail in severe winds, windstorms, or gales. You also add this bonus to foundering checks and capsizing checks for that ship. This bonus improves by +1 per 4 caster levels, to a maximum of +8.</p><p>The <em>stormrunner's ward</em> does nothing to protect the crew from the winds and green water that might roll over the side of the ship.</p>",
    "Material Component: Handful of copper powder.",
    null,null),
    
    (639,3,"Stormwalk","Conjuration","Teleportation",null,"V, S, DF",
    "1 full round","Touch",null,"You and up to one other creature for every two levels","Instantaneous",
    "None and Will negates (object)","No and Yes (object)",
    "Teleport youself and one creature/2 levels from a storm.",
    "<p>As <em>teleport</em>, save that you draw upon the power of a storm to teleport yourself and a number of others from one place to another.</p><p>Upon casting the spell, the storm suddenly intensifies in the area where the spell was cast, obscuring sight of those affected - whether because of a thickening of fog, a sudden increase in the downfall of hail and sleet, or a strike of lightning. On the next round, the disturbance disappears and the characters affected by the spell are gone.</p><p>Though the targets of the spell disappears instantaneously once the spell is cast, they do not immediately reappear at the spell's destination. Instead, 10 minutes elapse during which a storm quickly develops in the target location. This is plainly not a natural occurance to anyone who witnesses it, unless there is already a storm in progress.</p><p>Then an intensification of this storm obscures sight at the target location, and the targets of the spell reappear. The targets always appear in some place that is open to the storm - thus, they can appear on the upper parapets of a castle, but not inside the castle.</p><p>Though 10 minutes have passed since they disappeared, it appears to the travelers as though the transport were instantaneous. Additionally, for the 10 minutes while the targets are gone, they are treated as though they were in another plane.</p>",
    null,null,null),
    
    (640,3,"Swim","Transmutation",null,"Water","V, S, M",
    "1 round","Medium",null,"One creature","10 min./level (D)",
    "None","Yes (harmless)",
    "Subject gains swim speed and +8 bonus on Swim checks.",
    "<p>This spell gives the recipient a swim speed equal to its land speed (though not the ability to breathe water or hold its breath beyond normal limits). So long as the creature isn't carrying more than a light load, it can swim at its normal speed without making Swim checks. It also gains a +8 competence bonus on any Swim check to perform some special action or avoid a hazard. The creature can choose to take 10 on a Swim check, even if distracted or endangered. It can use the run action while swimming, provided it swims in a straight line.</p><p>If the creature is carrying more than a light load, it must make Swim checks to move (taking the normal penalty for weight carried), but all other benefits and bonuses of the spell still apply.</p>",
    "Arcane Material Component: A goldfish scale.",
    null,null),
    
    (641,3,"Tern's Persistence","Transmutation",null,null,"V, S, M/DF",
    "1 standard action","Touch",null,"Creature touched","24 hours",
    "Will negates (harmless)","Yes (harmless)",
    "",
    "<p>The subject gains the sea bird's ability to travel great distances without undue exertion. The subject can travel overland 50% longer than normal before risking injury or fatigue. For example, a character can walk up to 12 hours overland before having to make Constitution checks to avoid fatigue, or can hustle for 90 minutes before taking nonlethal damage. The subject still can't run for extended periods but it can move at run speed tactically for a number of rounds equal to 1-1/2 times its Constitution score.</p>",
    "Arcane Material Component: A few feathers or a pinch of guano from a tern.",
    null,null),
    
    (642,3,"Thalassemia","Necromancy",null,null,"V, S",
    "1 standard action","Touch",null,"Living creature touched","Instantaneous",
    "Fortitude half; see text","Yes",
    "Turn blood to seawater, dealing 1d6/level damage.",
    "<p>This spell thins the target creature's blood to little more than seawater, dealing 1d6 points of damage per level (maximum 15d6). Only living creatures with a circulatory system and blood can be affected by this spell; it does not harm creatures immune to critical hits. Creatures with the fire subtype instead take 1d8 points of damage per level.</p>",
    null,null,null),
    
    (643,3,"Tojanida Sight","Divination",null,null,"S",
    "1 standard action","Personal",null,"You","10 min./level (D)",
    null,null,
    "Gain all-around vision.",
    "<p>You gain all-around vision, allowing you to see in any direction. You gain a +4 bonus on Spot and Search checks, and you cannot be flanked for the duration of the spell. However, you cannot avert your eyes when confronted by a creature with a gaze attack, though you can still close your eyes in such a circumstance.</p>",
    null,null,null),
    
    (644,3,"Transformation of the Deeps","Transmutation",null,null,"V, S, M",
    "1 standard action","Touch",null,"One creature/3 levels","1 hour/level (D)",
    "None","Yes (harmless)",
    "Grant water breathing, darkvision, and pressure immunity to one creature/3 levels.",
    "<p>The creature you touch undergoes a transformation that allows it to survive in the terrible lightless depths of the oceans. This creates subtle changes in the spell's target, whose eyes become completely black and whose flesh becomes hard and cold.</p><p>The target of this spell gains the ability to breathe water and is rendered immune to damage from both the temperature and the pressure in extreme depths of water. Additionally, she gains darkvision out to 60 feet.</p>",
    "Material Component: A bit of stone or mud from a deep ocean trench",
    null,null),
    
    (645,3,"Tubidity","Abjuration",null,null,"S, M",
    "1 standard action","0 ft.","20-ft.-radius spread, centered on you",null,"1 min./level",
    "None","No",
    "Water surrounding you becomes cloudy, granting concealment.",
    "<p>You cause the water surrounding you to swirl and fill with suspended sediments, decreasing visibility and making it harder for foes to attack you. This roiling cloud obscures all vision, including darkvision, beyond 5 feet. Creatures within the area up to 5 feet from an attacker have concealment (20% miss chance), while those farther away have total concealment (50% miss chance). Creatures other than you within this cloud must make a Concentration check to cast a spell (DC 15 + spell level). Ranged attacks that pass through the <em>turbidity</em> automatically fail.</p><p>A vigorous current (1-3 knots) disperses the clouded water in 4 rounds; a dangerous or stronger current (4 or more knots) disperses it within 1 round.</p><p>This spell only functions underwater</p>",
    "Material Component: A handful of mud.",
    null,null),
    
    (646,3,"Urchin's Spines","Transmutation",null,null,"V, S, M/DF",
    "1 standard action","Touch",null,"Creature touched","1 min./level",
    "Will negates; see text (harmless)","Yes (harmless)",
    "Target grows spines that damage opponents.",
    "<p>The transmuted creature's skin (including clothing and armor) is covered by 2-inch spines. An opponent who grapples the subject or strikes it with a natural weapon takes 1d3 points of piercing damage from the spines, which also inject a mildly irritating poison. The opponent must make a DC 13 Fortitude save or take initial and secondary damage of 1d2 Dexterity.</p>",
    "Arcane Material Component: A spine from a sea urchin",
    null,null),
    
    (647,3,"Wake Trailing","Divination",null,"Water","V, S, M",
    "1 standard action","Touch",null,"One ship","24 hours",
    "None","No",
    "You can track a ship across the sea.",
    "<p>You are able to track a vessel over open water by following flotsam and other signs of a ship's recent presence. These signs of passage are relatively subtle, but as long as the spell is active you can find those signs on a survival check, as though you were tracking a Huge, Gargantuan, or Colossal creature (depending on the size of the ship) over soft ground. The following modifiers are used in place of those given on page 101 of the <em>Player's Handbook</em>. The caster must have the Track feat to use this spell.</p><table><thead><tr><th><strong>Condition</strong></th><th><strong>Survival DC Modifier</strong></th></tr></thead><tbody><tr><td>Every 4 hours since the trail was made</td><td>+1</td></tr><tr><td>Every hour of water-affecting weather since the trail was made</td><td>+1</td></tr><tr><td>Trail leads through vigorous currents</td><td>+2</td></tr><tr><td>Trail leads through dangerous or stronger currents</td><td>+5</td></tr><tr><td>Poor visibility (apply only the largest):</td></tr><tr><td>Moonlight</td><td>+3</td></tr><tr><td>Fog or precipitation</td><td>+3</td></tr><tr><td>Overcast or moonless night</td><td>+6</td></tr></tbody></table><p>If multiple ships have passed in a given area, you can track a specific ship only if you have some knowledge of the size or type of the ship, or other knowledge that differentiates that ship from the other vessels (for instance, if you know the ship is made from a unique type of wood or is crewed by minotaurs).</p>",
    "Material Component: A bit of driftwood wrapped with red thread.",
    null,null),
    
    (648,3,"Water to Acid","Transmutation",null,"Water","V, S, M",
    "1 standard action","Medium","Up to 1 cu. ft./level",null,"Instantaneous",
    "None","No",
    "Transforms 1 cu. ft./level of water into acid.",
    "<p>You transform a volume of water into an equal volume of acid, which deals damage to creatures that come into contact with it. You cannot transform water inside a creature's body, but you can affect water surrounding it. Water containing more than a trace of dissolved or suspended substances can't be affected by this spell.</p><p>You can fill a flask with acid produced this way and throw it as a splash weapon that deals 1d6 points of acid damage on a direct hit and 1 point of acid damage from a splash (see page 128 of the <em>Player's Handbook</em>).</p><p>Each round a creature is in contact with the acid, it takes 1d6 points of acid damage. Underwater, the acid created by this spell dissipates after 1 round/caster level.</p><p>The acid dissolves metallic objects it contacts. It deals 1d6 points of damage per round and ignores the objects hardness. A magic item makes a Fortitude saving throw each round for half damage.</p>",
    "Material Component: A few drops of vinegar.",
    null,null),
    
    (649,3,"Waterspout","Conjuration","Creation",null,"V, S, DF",
    "1 full round","Long","Cylinder 10 ft. wide and 80 ft. tall",null,"1 round/level",
    "Reflex negates","No",
    "Water rises up into a whirling vortex that deals 3d8 points of damage and sucks creatures in.",
    "<p><em>Waterspout</em> causes water to rise up into a whirling, cylindrical column that looks exactly like a tornado made of water. A body of water at least 10 feet wide and 20 feet deep must be present, or the spell is wasted. If the waterspout encounters insufficient depth after it has formed, it collapses.</p><p>The waterspout moves at a speed of 30 feet and must remain over water. You can concentrate on controlling the waterspout's every movement or specify a simple program, such as move straight ahead, zigzag, circle, or the like. Directing the waterspout's movement or changing its programmed movement or changing its programmed movement is a standard action for you. The waterspout always moves during your turn in the initiative order. If the waterspout exceeds the spell's range, it collapses and the spell ends.</p><p>The waterspout batters creatures and objects it touches, and it often sucks them up inside its vortex. Any creature or object that comes in contact with the waterspout must succeed on a Reflex save or take 3d8 points of damage. Medium or smaller creatures who fail their save are sucked into the waterspout and whirled about inside its powerful currents, taking 2d6 points of damage each round with no save allowed. Trapped creatures remain inside for 1d3 rounds before the waterspout ejects them out the top of the spout, and they fall back to the surface (taking fall damage) 1d8x5 feet from the base of the waterspout.</p><p>Waterborne creatures or objects within 10 feet of the spout (below and on all sides) also must make Reflex saves or be sucked into the spout if they are Medium or smaller. Anything sucked into the spout taked 3d8 points of damage and is then trapped for 1d3 rounds as explained above.</p><p>Only the smallest boats - canoes, kayaks, coracles, and the like - can be sucked into the spout. The occupant of any such craft can make a Profession (sailor) check instead of a Reflex save to avoid being sucked into the waterspout.</p>",
    null,null,null),
    
    (650,3,"Wave Blessing","Transmutation",null,"Water","V",
    "1 immediate action","Medium",null,"One Medium or smaller object or creature/level, no two of which can be more than 30 ft. apart","10 min/level",
    "None","Yes (harmless)",
    "Keeps one creature/level from sinking.",
    "<p>On the seas, there is always the danger of falling overboard, especially to those wearing armor or who simply cannot swim.</p><p>The affected targets do not go under the water if they fail a Swim check for any reason, including being tied up, unconscious, or heavily loaded. However, the targets can still be dragged under by the actions of other creatures.</p><p>You can cast this spell with an instant utterance. Casting this spell is an immedaite action. You can even cast this spell when it isn;t your turn.</p><p><em>Wave blessing</em> counters and dispels <em>sink</em>.</p>",
    null,null,null),
    
    (651,3,"Webfoot","Transmutation",null,null,"V, S, DF",
    "1 standard action","Touch",null,"Creature touched","10 min./level",
    "Will negates (harmless)","Yes (harmless)",
    "Target gains +4 on Swim and is less hindered by bog terrain.",
    "<p>The transmuted creature becomes better acclimated to wetlands and watery environments. It gains a +4 bonus on Swim checks and is not hindered when moving through shallow bog terrain. It treats an area of deep bog as shallow bog for purposes of movement and Tumble checks (see Marsh Terrain on page 88 of the <em>Dungeon Master's Guide</em>).</p>",
    null,null,null);