INSERT INTO Wondrous_Item 
    (Book_ID,Magic_Item_Name,Magic_Item_Description,Magic_Item_Caster_Level,
    Magic_Item_Cost,Magic_Item_Aura,Magic_Item_Creation_Reqs) 
    VALUES

    (3,"Admiral's Bicorne",
        "<p>This elaborately braided headgear is made of rich blue felt, embroidered with golden thread. It often has a showy badge called a cockade, proclaiming nationality, faith, family crest, and the like.</p><p>A humanoid or monstrous humanoid who dons the <em>admiral's bicorne</em> gains a +5 bonus on Profession (sailor) checks and all Charisma-based checks (including Leadership) as long as it is worn. The wearer's voice is magically amplified, so that it can be heard clearly by anyone within 100 feet; class features and effects that depend on hearing the speaker benefit from the increased range. Finally, the <em>admiral's bicorne</em> grants a +2 morale bonus on attack rolls, saves, and skill checks to allies within sound of the wearer's voice (including the wearer).",
        10,51000.00,"Strong conjuration",
        "CL 10th, Craft Wondrous Item, eagle's splendor, heroism, owl's wisdom, ventriloquism"),
        
    (3,"Bag of Teeth",
        "<p>This small sack is made of fish skin and contains a handful of piranha teeth. By opening the bag and scattering its contents in a body of water, the user creates a piranha swarm (see page 162 of <em>Stormwrack</em>).</p><p>The swarm is average in all regards and remains for 10 minutes. The swarm moves toward and attacks the closest living creature in the water, and the user has no control over its target or direction of travel. If no other creature is available, the swarm remains where it was summoned and attacks the first creature that approaches.</p>",
        13,2000.00,"Strong conjuration",
        "CL 13th, Craft Wondrous Item, summon swarm"),
        
    (3,"Captain's Lantern",
        "<p>This exquisite brass and green-glass lantern constantly protects the ship to which it is attuned with an <em>alarm</em> effect. The captain of the ship can speak a command word while touching a copper coin to the underside of the lantern to create a lantern token. Those who possess a lantern token do not set off the <em>alarm</em>. The captain can turn the <em>alarm</em> on or off with a command word. The captain can, at any time, negate all the current lantern tokens, turning them back into nonmagical copper coins. Tokens radiate a very minor abjuration effect.</p>",
        3,12000.00,"Faint abjuration",
        "CL 3rd, Craft Wondrous Item, alarm"),
        
    (3,"Everfull Sails",
        "<p>Sails crafted of a sky-blue canvas with strange silver flecking, these magical sails are always filled with a strong wind when fully unfurled. The wind created behind the sails is sufficient to drive the ship forward at its full normal speed, and the sails ignore any other winds that might be blowing contrary to that generated by the sails themselves. The winds stop when the sails are furled or otherwise pulled down.</p><p>A ship requires one set of <em>everfull sails</em> per mast, or the magic does not function (although the sails work as normal sails).</p>",
        3,12000.00,"Moderate evocation [air]",
        "CL 3rd, Craft Wondrous Item, gust of wind"),
        
    (3,"Figure of Wondrous Power (Pearlsteel Turtle)",
        "<p>This miniature statuette of a sea turtle is about the size of a human hand. Tossing down the figurine and uttering the command word causes it to transform into a giant sea turtle. The creature obeys and serves its owner; it understands Common but does not speak.</p><p>The giant sea turtle described here is a Huge version of a common sea turtle and is not aggressive. It serves only as a transport and does not obey orders to attack, although it will defend itself if threatened.</p><br><p><strong>Giant Turtle</strong>: CR 3; Huge magical beast (aquatic); HD 8d10+32; hp 87; Init +0; Speed 20 ft., swim 30 ft.; AC 25, touch 8, flat-footed 25; Base Atk +8; Grp +23; Atk or Full Atk +13 melee (1d8+3, bite)*; Space/Reach 15 ft./10 ft. (bite 10 ft.); SQ darkvision 60 ft., hold breath, low-light vision; AL N; SV Fort +10, Ref +6, Will +6; Str 25, Dex 10, Con 19, Int 6, Wis 14, Cha 6.</p><p>*A giant turtle's bite is treated as a secondary attack and adds only half the creature's Strength bonus to the damage roll.</p><p><em>Skills and Feats</em>: Listen +10, Spot +9, Swim +12; Alertness, Iron Will.</p><p><em>Languages</em>: Common (does not speak).</p><p><strong>Hold Breath (Ex):</strong> A giant turtle can hold its breath for 1 hour before it risks drowning.</p><p><strong>Skills:</strong> A giant turtle has a +8 racial bonus on any Swim check to perform some special action or avoid a hazard. It can always choose to take 10 on a Swim check to perform some special action or avoid a hazard. It can always choose to take 10 on a Swim check, even if distracted or endangered. It can use the run action while swimming, provided it swims in a straight line.</p><br><p>This creature can be harnessed to pull a boat or raft at up to one half its swim speed. It is possible to ride on the turtle's shell, but doing so requires a harness or rope or improvising handholds. Hanging onto the slick shell while the animal moves is extremely difficult, requiring a DC 20 Ride check each minute of travel.</p><p>The <em>pearlsteel turtle</em> can be used up to three times per week for up to 6 hours at a time.</p>",
        11,10000.00,"Moderate transmutation",
        "CL 11th, Craft Wondrous Item, animate objects"),
        
    (3,"Finned Gauntlets",
        "<p>These sharkskin gauntlets are adorned with sweeping fins. The wearer gains a natural swim speed of 30 feet, with a +8 competence bonus on Swim checks to perform some special action or avoid a hazard. The wearer can always take 10 on a Swim check, even if distracted or endangered, and can use the run action while swimming. Both gloves must be worn for the magic to be effective.</p>",
        5,10000.00,"Faint transmutation",
        "CL 5th, Craft Wondrous Item, alter self"),
        
    (3, "Living Figurehead [skeleton]",
        "<p>Each of the several kinds of <em>living figureheads</em> is carved from fine wood and resembles an ordinary figurehead. When a command word is spoken, the figurehead animates and is able to use special powers as described below. The <em>living figurehead</em> obeys and serves the ship's master (usually the captain). Unless stated otherwise, it can speak Common and communicate telepathically with its master, provided it is within 100 feet.</p><p>If a <em>living figurehead</em> is broken or destroyed in its carving form, it is forever ruined. If destroyed while animated, it simply reverts to a wooden carving that can be used again at a later time.</p><p>An animated <em>living figurehead</em> is a construct of the same size as the object (see Animated Object on page 12 of the <em>Monster Manual</em>), but it has the Intelligence, Wisdom, and Charisma scores given in its entry. Special abilities whose save DCs depend on Constitution use the animated figurehead's Charisma score instead.</p>");