INSERT INTO Weapon (Book_ID, Weapon_Name, Weapon_Category, Weapon_Type, Weapon_Cost,
    Weapon_Small_Damage, Weapon_Medium_Damage, Weapon_Critical, Weapon_Range_Increment,
    Weapon_Damage_Type, Weapon_Weight, Weapon_Rarity, Weapon_Description)
VALUES

    (3, "Cutlass", "Martial", "Light Melee", 15.00, "1d4", "1d6", "19-20/x2", null, "S", 3.00, "Common",
    "<p>A light slashing weapon especially favored by pirates and other nautical raiders, the cutlass is a heavy blade about 2 feet long with a curved edge. It is easy to wield in close quarters and can deal vicious gashes to an opponent. Its heavy basket hilt gives the wielder a +2 circumstance bonus on any checks to resist being disarmed.</p>"),
    
    (3, "Longbow, Aquatic", "Martial", "Ranged", 400.00, "1d6", "1d8", "x3", 60, "P", 3.00, "Uncommon",
    "<p>Made by the aquatic elves, the aquatic longbow functions as a normal ranged weapon out of the water, with a 60-foot range increment. Underwater, it has a range increment of 10 feet, but it does not take the normal penalty for a ranged attack through water. If you have the Aquatic Shot feat, the aquatic longbow's range increment improves to 30 feet underwater. Aquatic longbows are favored by aquatic elves.</p>"),
    
    (3, "Stingray Whip", "Exotic", "One-Handed Melee", 15.00, "1d4", "1d6", "x3", 10, "P or S", 3.00, "Uncommon",
    "<p>The barbed tail of a stingray can be converted into a flexible weapon, something akin to a riding crop. A stingray whip deals no damage to any creature with a +2 or higher armor bonus or natural armor bonus +4 or higher.</p><p>You can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with a stingray whip sized for you, even though it isn't a light weapon for you.</p><p>The stingray tail no longer contains poison glands, but a residue of its venom remains. A creature that takes damage from the stingray whip must make a DC 12 Fortitude save or take a -1 penalty on attack rolls, damage rolls, and skill checks from painful welts.</p><p>Treat a stingray whip as leather for the purpose of sunder attempts.</p>"),
    
    (3, "Crossbow, Aquatic", "Exotic", "Ranged", 250.00, "1d6", "1d8", "19-20/x2", 40, "P", 4.00, "Uncommon",
    "<p>This special version of a light crossbow is strung especially tautly with thicker wire and reinforced so as not to snap under the increased tension. The aquatic crossbow is not subject to the normal -2 penalty on ranged attack rolls for every five feet of distance (see Ranged Attacks Underwater, page 93 of the Dungeon Master's Guide), and uses its normal range increment of 40 feet both in and out of the water. Aquatic crossbows are favored by aventi, merfolk, and tritons.</p>"),
    
    (3, "Harpoon", "Exotic", "Ranged", 15.00, "1d8", "1d10", "x2", 30, "P", 10.00, "Common",
    "<p>The harpoon is a broad-bladed spear forged with barbs. The shaft of the harpoon has a trailing rope attached, to control harpooned opponents. Though designed for hunting whales and other large sea creatures, the harpoon can be used on dry land.</p><p>If it deals damage, the harpoon lodges in an opponent who fails a Reflex saving throw (DC 10 + the damage dealt). A harpooned creature moves at only half speed and cannot charge or run. If you control the trailing rope by succeeding on an opposed Strength check while holding it, the harpooned creature can move only within the limits that the rope allows (the trailing rope is 30 feet long). If the harpooned creature attempts to cast a spell, it must succeed on a DC 15 Concentration check or lose the spell.</p><p>The harpooned creature can attempt to pull the harpoon from its wound if it has two free hands and takes a full-round action to do so, but it deals damage to itself equal to the initial damage the harpoon dealt. A character who succeeds on a DC 15 Heal check can remove a harpoon without further damage.</p>"),
    
    (3, "Skipping Blade (3)", "Exotic", "Ranged", 1.00, "1d2", "1d3", "x3", 10, "S", 0.50, "Uncommon",
    "<p>This is a double-bladed throwing weapon, about the size of a shuriken but heavier. A skipping blade can't be used as a melee weapon.</p><p>The blade is carefully shaped to allow skipping across water or another liquid surface. The weapon's range increment is increased to 15 feet if there is an intervening body of water between the attacker and the opponent.</p><p>Although they are thrown weapons, skipping blades are treated as ammunition for the purposes of drawing them, crafting masterwork or otherwise special versions of them, and what happens to them after they are thrown.</p>");